In [137]:
# package imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Suppress all scientific notation
pd.options.display.float_format = '{:20,.2f}'.format

#see max columns, global setting DO THIS AFTER PIVOTING
#pd.set_option('display.max_columns', None)
#see max rows
#pd.set_option('display.max_rows', None)

In [138]:
#Importing JUST Capital-developed functions
from justcapital import api_call as jc_api

In [139]:
#Getting raw 2021 rankings
rankings_2021_raw = jc_api.get_data("apim_ss_ft_models_for_companies_2021_forbes",
                               ["fields=company_perm_id, model_slug, value, value_type",
                                "value_type=in:'rank'"])
rankings_2021_raw

                 company_perm_id      model_slug  value value_type
0      0040f5f17ffc61944024e975e           WAGES    254       rank
1      00aa86290f0973a72bca4ef3b           WAGES    481       rank
2      00dae748aa57b455fb29eac00           WAGES    730       rank
3      00fb5c9ebbdc6c359d2e001c6           WAGES    208       rank
4      010e3acd01fb1bb37db745be9           WAGES     72       rank
...                          ...             ...    ...        ...
23195  fe9668a59a7386ac1e898d980  WEIGHTED_SCORE    169       rank
23196  feba29952d39a2b39d6b58481  WEIGHTED_SCORE    543       rank
23197  fee1881a18aa180338c3fe312  WEIGHTED_SCORE    562       rank
23198  ff7db7310ab5270accf0422e1  WEIGHTED_SCORE     29       rank
23199  ffedba4233ac1a8729cd5749d  WEIGHTED_SCORE     22       rank

[23200 rows x 4 columns]

In [140]:
#Pivoting to index by company_perm_id, makes slugs columns
rankings_2021_pivot = rankings_2021_raw.pivot(index ='company_perm_id',
                                                    columns ='model_slug',
                                                    values ='value')
rankings_2021_pivot

model_slug,BENEFITS,CAREER,CLIMATECHANGE,COMM,COMMDEV,CUST,DEI,ENV,ENVEFFICIENT,EXPERIENCE,...,PRIVACY,PRODHARM,RESPONSIBLE,SHARE,SUPPLY_CHAIN,SUSTPRODUCTSERVICE,TRANSPARENT,WAGES,WEIGHTED_SCORE,WORKER
company_perm_id,,,,,,,,,,,,,,,,,,,,,
0040f5f17ffc61944024e975e,458,841,843,93,79,871,309,867,814,800,...,732,695,767,620,74,481,1,254,440,440
00aa86290f0973a72bca4ef3b,488,701,299,811,658,242,426,315,503,653,...,122,75,842,858,304,318,1,481,613,446
00dae748aa57b455fb29eac00,677,785,1,313,367,593,426,415,469,522,...,560,318,1,8,131,495,1,730,531,804
00fb5c9ebbdc6c359d2e001c6,689,86,116,225,498,334,426,317,76,448,...,226,300,100,443,221,751,1,208,204,220
010e3acd01fb1bb37db745be9,280,558,116,18,124,2,46,38,45,1,...,19,85,345,277,35,56,1,72,16,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,816,646,383,94,651,51,82,493,93,33,...,560,6,360,271,34,858,1,716,169,465
feba29952d39a2b39d6b58481,458,259,667,785,498,309,426,624,514,581,...,226,85,628,524,228,835,1,481,543,547
fee1881a18aa180338c3fe312,706,900,299,575,658,551,426,446,236,678,...,365,300,100,187,304,751,1,716,562,675
ff7db7310ab5270accf0422e1,33,174,116,36,465,544,32,43,350,808,...,560,54,605,523,71,41,1,82,29,15
ffedba4233ac1a8729cd5749d,66,240,588,28,33,37,35,584,709,128,...,67,50,1,29,1,127,1,592,22,72

In [141]:
#Adding a suffix to all columns in this table. That way, we know which year it refers to
rankings_2021 = rankings_2021_pivot.add_suffix('_21')
rankings_2021

model_slug,BENEFITS_21,CAREER_21,CLIMATECHANGE_21,COMM_21,COMMDEV_21,CUST_21,DEI_21,ENV_21,ENVEFFICIENT_21,EXPERIENCE_21,...,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SHARE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21,WEIGHTED_SCORE_21,WORKER_21
company_perm_id,,,,,,,,,,,,,,,,,,,,,
0040f5f17ffc61944024e975e,458,841,843,93,79,871,309,867,814,800,...,732,695,767,620,74,481,1,254,440,440
00aa86290f0973a72bca4ef3b,488,701,299,811,658,242,426,315,503,653,...,122,75,842,858,304,318,1,481,613,446
00dae748aa57b455fb29eac00,677,785,1,313,367,593,426,415,469,522,...,560,318,1,8,131,495,1,730,531,804
00fb5c9ebbdc6c359d2e001c6,689,86,116,225,498,334,426,317,76,448,...,226,300,100,443,221,751,1,208,204,220
010e3acd01fb1bb37db745be9,280,558,116,18,124,2,46,38,45,1,...,19,85,345,277,35,56,1,72,16,121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,816,646,383,94,651,51,82,493,93,33,...,560,6,360,271,34,858,1,716,169,465
feba29952d39a2b39d6b58481,458,259,667,785,498,309,426,624,514,581,...,226,85,628,524,228,835,1,481,543,547
fee1881a18aa180338c3fe312,706,900,299,575,658,551,426,446,236,678,...,365,300,100,187,304,751,1,716,562,675
ff7db7310ab5270accf0422e1,33,174,116,36,465,544,32,43,350,808,...,560,54,605,523,71,41,1,82,29,15
ffedba4233ac1a8729cd5749d,66,240,588,28,33,37,35,584,709,128,...,67,50,1,29,1,127,1,592,22,72

In [142]:
rankings_2021.columns

Index(['BENEFITS_21', 'CAREER_21', 'CLIMATECHANGE_21', 'COMM_21', 'COMMDEV_21',
       'CUST_21', 'DEI_21', 'ENV_21', 'ENVEFFICIENT_21', 'EXPERIENCE_21',
       'HEALTH_21', 'JOBS_21', 'PERFORMANCE_21', 'PHILANTHROPY_21',
       'PRIORITIZATION_21', 'PRIVACY_21', 'PRODHARM_21', 'RESPONSIBLE_21',
       'SHARE_21', 'SUPPLY_CHAIN_21', 'SUSTPRODUCTSERVICE_21',
       'TRANSPARENT_21', 'WAGES_21', 'WEIGHTED_SCORE_21', 'WORKER_21'],
      dtype='object', name='model_slug')

In [143]:
#Getting raw 2022 rankings
#Includes Issues, Stakeholders, and Overall ranks

rankings_2022_raw = jc_api.get_data("ft_ss_model_ranking_RANKING_2022_WEIGHT_SCHEMA22_AYR_2022",
                               ["fields=company_perm_id, model_slug, industry_rank, overall_rank",
                                "model_slug=in:'WAGES','JOBS','PRIORITIZATION','HEALTH','RESPONSIBLE','BENEFITS','DEI','SUSTPRODUCTSERVICE','PRIVACY','CAREER','SUPPLY_CHAIN','EXPERIENCE','POLLUTION','COMMDEV','CLIMATECHANGE','TRANSPARENT','PRODHARM','RESOURCES','PERFORMANCE','PHILANTHROPY','COMM','CUST','ENV','SHARE','WORKER','WEIGHTED_SCORE'"])
rankings_2022_raw

,company_perm_id,model_slug,industry_rank,overall_rank
0,00aa86290f0973a72bca4ef3b,RESOURCES,16,384
1,00aa86290f0973a72bca4ef3b,POLLUTION,32,705
2,00aa86290f0973a72bca4ef3b,SUSTPRODUCTSERVICE,9,373
3,00aa86290f0973a72bca4ef3b,CLIMATECHANGE,18,499
4,00aa86290f0973a72bca4ef3b,PERFORMANCE,27,303
...,...,...,...,...
24799,ffedba4233ac1a8729cd5749d,SHARE,10,240
24800,ffedba4233ac1a8729cd5749d,CUST,2,225
24801,ffedba4233ac1a8729cd5749d,COMM,7,223
24802,ffedba4233ac1a8729cd5749d,WORKER,7,121
24803,ffedba4233ac1a8729cd5749d,WEIGHTED_SCORE,2,90

In [144]:
#Pivoting to index by company_perm_id, makes slugs columns
rankings_2022_pivot = rankings_2022_raw.pivot(index ='company_perm_id',
                                                    columns ='model_slug',
                                                    values ='overall_rank')
rankings_2022_pivot

model_slug,BENEFITS,CAREER,CLIMATECHANGE,COMM,COMMDEV,CUST,DEI,ENV,EXPERIENCE,HEALTH,...,PRODHARM,RESOURCES,RESPONSIBLE,SHARE,SUPPLY_CHAIN,SUSTPRODUCTSERVICE,TRANSPARENT,WAGES,WEIGHTED_SCORE,WORKER
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,757,906,499,920,653,376,298,597,277,439,...,328,384,795,479,483,373,1,617,686,671
00dae748aa57b455fb29eac00,204,441,219,448,239,584,570,405,277,273,...,459,655,1,51,98,390,1,394,276,343
010e3acd01fb1bb37db745be9,372,793,10,165,18,1,23,9,70,79,...,2,186,480,11,56,45,1,732,27,358
01722398f1dd91d629c842eae,380,1,863,168,42,834,298,800,277,73,...,860,584,378,26,454,862,1,1,35,7
01d76805a4a4900d37767bcf2,222,217,184,376,199,225,298,70,277,630,...,527,564,115,582,82,1,1,346,282,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,269,527,32,177,601,215,23,96,133,263,...,111,129,521,420,53,217,1,891,265,512
feba29952d39a2b39d6b58481,405,270,824,370,653,724,548,874,277,167,...,2,789,115,434,79,862,1,520,463,405
fee1881a18aa180338c3fe312,518,655,727,714,653,193,571,704,277,439,...,70,722,507,708,237,438,1,777,723,698
ff7db7310ab5270accf0422e1,361,345,208,373,347,625,95,382,277,137,...,380,421,770,537,91,397,1,354,298,166
ffedba4233ac1a8729cd5749d,90,74,38,223,1,225,23,81,277,458,...,527,317,55,240,78,106,1,483,90,121

In [145]:
#Adding a suffix to all columns in this table. That way, we know which year it refers to
rankings_2022 = rankings_2022_pivot.add_suffix('_22')
rankings_2022

model_slug,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,COMMDEV_22,CUST_22,DEI_22,ENV_22,EXPERIENCE_22,HEALTH_22,...,PRODHARM_22,RESOURCES_22,RESPONSIBLE_22,SHARE_22,SUPPLY_CHAIN_22,SUSTPRODUCTSERVICE_22,TRANSPARENT_22,WAGES_22,WEIGHTED_SCORE_22,WORKER_22
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,757,906,499,920,653,376,298,597,277,439,...,328,384,795,479,483,373,1,617,686,671
00dae748aa57b455fb29eac00,204,441,219,448,239,584,570,405,277,273,...,459,655,1,51,98,390,1,394,276,343
010e3acd01fb1bb37db745be9,372,793,10,165,18,1,23,9,70,79,...,2,186,480,11,56,45,1,732,27,358
01722398f1dd91d629c842eae,380,1,863,168,42,834,298,800,277,73,...,860,584,378,26,454,862,1,1,35,7
01d76805a4a4900d37767bcf2,222,217,184,376,199,225,298,70,277,630,...,527,564,115,582,82,1,1,346,282,339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,269,527,32,177,601,215,23,96,133,263,...,111,129,521,420,53,217,1,891,265,512
feba29952d39a2b39d6b58481,405,270,824,370,653,724,548,874,277,167,...,2,789,115,434,79,862,1,520,463,405
fee1881a18aa180338c3fe312,518,655,727,714,653,193,571,704,277,439,...,70,722,507,708,237,438,1,777,723,698
ff7db7310ab5270accf0422e1,361,345,208,373,347,625,95,382,277,137,...,380,421,770,537,91,397,1,354,298,166
ffedba4233ac1a8729cd5749d,90,74,38,223,1,225,23,81,277,458,...,527,317,55,240,78,106,1,483,90,121

In [146]:
#Left Joining 2021 onto 2022 rankings
#Includes Issues, Stakeholders, and Overall ranks
#Though the title is 'all_ranks_2022', it does include Issue, Stakeholder, and Overall ranks from 2021.
#2022 refers to the companies in the left-most column
all_ranks_2022 = pd.merge(rankings_2022, rankings_2021, how="left", on="company_perm_id")
all_ranks_2022

model_slug,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,COMMDEV_22,CUST_22,DEI_22,ENV_22,EXPERIENCE_22,HEALTH_22,...,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SHARE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21,WEIGHTED_SCORE_21,WORKER_21
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,757,906,499,920,653,376,298,597,277,439,...,122.00,75.00,842.00,858.00,304.00,318.00,1.00,481.00,613.00,446.00
00dae748aa57b455fb29eac00,204,441,219,448,239,584,570,405,277,273,...,560.00,318.00,1.00,8.00,131.00,495.00,1.00,730.00,531.00,804.00
010e3acd01fb1bb37db745be9,372,793,10,165,18,1,23,9,70,79,...,19.00,85.00,345.00,277.00,35.00,56.00,1.00,72.00,16.00,121.00
01722398f1dd91d629c842eae,380,1,863,168,42,834,298,800,277,73,...,560.00,398.00,377.00,587.00,602.00,481.00,1.00,321.00,415.00,281.00
01d76805a4a4900d37767bcf2,222,217,184,376,199,225,298,70,277,630,...,67.00,398.00,100.00,93.00,203.00,565.00,1.00,216.00,189.00,301.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,269,527,32,177,601,215,23,96,133,263,...,560.00,6.00,360.00,271.00,34.00,858.00,1.00,716.00,169.00,465.00
feba29952d39a2b39d6b58481,405,270,824,370,653,724,548,874,277,167,...,226.00,85.00,628.00,524.00,228.00,835.00,1.00,481.00,543.00,547.00
fee1881a18aa180338c3fe312,518,655,727,714,653,193,571,704,277,439,...,365.00,300.00,100.00,187.00,304.00,751.00,1.00,716.00,562.00,675.00
ff7db7310ab5270accf0422e1,361,345,208,373,347,625,95,382,277,137,...,560.00,54.00,605.00,523.00,71.00,41.00,1.00,82.00,29.00,15.00
ffedba4233ac1a8729cd5749d,90,74,38,223,1,225,23,81,277,458,...,67.00,50.00,1.00,29.00,1.00,127.00,1.00,592.00,22.00,72.00

Now to find the following for 2022 companies
- ticker
- company_name
- description
- industry_name
- marketcap

Then join them

I wasn't sure how to get this in Python, so instead I opted for the following SQL query, which returns the above meta-data for all the companies in the 2022 rankings;
```mysql
select distinct(a.company_perm_id), a.ticker, a.company_name, b.description, a.industry_name, a.marketcap
from ft_ss_raw_datapoints_data_approved_AYR_2022 a
left join ft_ss_companies_AYR_2022 b
on a.company_perm_id=b.perm_id
```

Then I saved and exported the file and uploaded it into the current folder as 'company_metadata.csv'

In [147]:
companies_info = jc_api.get_data("ft_ss_companies_AYR_2022",
                               ["fields=perm_id, name, ticker, description, jc_industry_perm_id, marketcap"
                                ])
industry_info = jc_api.get_data("ft_ss_industries_AYR_2022",
                               ["fields=name, jc_industry_perm_id"])

#inplace=True is another way of writing 'industry_info =', overwrite the old thing with the new thing
industry_info.rename(columns={'name': 'industry_name'}, inplace=True)
company_stuff = pd.merge(companies_info, industry_info, how="left", on="jc_industry_perm_id")
company_stuff

company_stuff.to_excel("company_stuff.xlsx",index = False)

In [148]:
weights = jc_api.get_data("ft_ss_data_weights_AYR_2022",
                               ["fields=weight_schema_perm_id, taxonomy_item_perm_id, weight",
                               "weight_schema_perm_id=in: '807b7771c21f9f3c0c251c43fe723417'" 
                               ])
taxonomy = jc_api.get_data("ft_ss_data_taxonomy_AYR_2022",
                               ["fields=perm_id, slug, name, description"
                               ])

weights_2022 = pd.merge(taxonomy, weights, how="left", left_on="perm_id", right_on="taxonomy_item_perm_id")
weights_2022 = weights_2022[weights_2022['weight'].notna()]
len(weights_2022)

weights_2022.to_excel("weights_2022.xlsx",index = False)

In [149]:
weights = jc_api.get_data("ft_ss_data_weights_AYR_2022",
                               ["fields=weight_schema_perm_id, taxonomy_item_perm_id, weight",
                               "weight_schema_perm_id=in: 'f7755752ab50b30bca10cb7856f53ec3'" 
                               ])
taxonomy = jc_api.get_data("ft_ss_data_taxonomy_AYR_2022",
                               ["fields=perm_id, slug, name, description"
                               ])

weights_2021 = pd.merge(taxonomy, weights, how="left", left_on="perm_id", right_on="taxonomy_item_perm_id")
weights_2021 = weights_2021[weights_2021['weight'].notna()]
len(weights_2021)

#weights_2022.to_excel("weights_2022.xlsx",index = False)

18

In [150]:
#read in company data file, naming the object so that comp contains this CSV file.
company_metadata = pd.read_csv("company_metadata.csv")
company_metadata

,company_perm_id,ticker,company_name,description,industry_name,marketcap
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00"
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00"
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00"
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00"
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00"
...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00"
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00"
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00"
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00"
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00"

In [151]:
#Updating 'all_ranks_2022' to include company_metadata
#Though the title is 'all_ranks_2022', it does include Issue ranks from 2021.
#2022 refers to the companies in the left-most column
all_ranks_2022 = pd.merge(company_metadata, all_ranks_2022, how="left", on="company_perm_id")
all_ranks_2022

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,...,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SHARE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21,WEIGHTED_SCORE_21,WORKER_21
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00",757,906,499,920,...,122.00,75.00,842.00,858.00,304.00,318.00,1.00,481.00,613.00,446.00
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00",204,441,219,448,...,560.00,318.00,1.00,8.00,131.00,495.00,1.00,730.00,531.00,804.00
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00",372,793,10,165,...,19.00,85.00,345.00,277.00,35.00,56.00,1.00,72.00,16.00,121.00
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00",380,1,863,168,...,560.00,398.00,377.00,587.00,602.00,481.00,1.00,321.00,415.00,281.00
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00",222,217,184,376,...,67.00,398.00,100.00,93.00,203.00,565.00,1.00,216.00,189.00,301.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00",269,527,32,177,...,560.00,6.00,360.00,271.00,34.00,858.00,1.00,716.00,169.00,465.00
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00",405,270,824,370,...,226.00,85.00,628.00,524.00,228.00,835.00,1.00,481.00,543.00,547.00
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00",518,655,727,714,...,365.00,300.00,100.00,187.00,304.00,751.00,1.00,716.00,562.00,675.00
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00",361,345,208,373,...,560.00,54.00,605.00,523.00,71.00,41.00,1.00,82.00,29.00,15.00
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00",90,74,38,223,...,67.00,50.00,1.00,29.00,1.00,127.00,1.00,592.00,22.00,72.00

In [152]:
#Defining the basic components like company name, industry, and marketcap as its own table, called 'base'
base = all_ranks_2022[['company_perm_id', 'ticker', 'company_name', 'description', 'industry_name', 'marketcap']]
base
#I believe this and company_metadata and company_metadata.csv are the same. So this step may be unnecessary

,company_perm_id,ticker,company_name,description,industry_name,marketcap
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00"
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00"
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00"
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00"
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00"
...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00"
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00"
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00"
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00"
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00"

In [153]:
#Defining a table as 'stakeholder' by taking only specific columns from the 'all_ranks' table
#Changing the order in which the columns are called will change the order of how they show up in the 'stakeholder' table
stakeholder = all_ranks_2022[['company_perm_id',
                              'WEIGHTED_SCORE_22', 'WEIGHTED_SCORE_21',
                              'COMM_22', 'COMM_21',
                              'CUST_22', 'CUST_21',
                              'ENV_22', 'ENV_21',
                              'SHARE_22', 'SHARE_21',
                              'WORKER_22', 'WORKER_21']]
stakeholder

,company_perm_id,WEIGHTED_SCORE_22,WEIGHTED_SCORE_21,COMM_22,COMM_21,CUST_22,CUST_21,ENV_22,ENV_21,SHARE_22,SHARE_21,WORKER_22,WORKER_21
0,00aa86290f0973a72bca4ef3b,686,613.00,920,811.00,376,242.00,597,315.00,479,858.00,671,446.00
1,00dae748aa57b455fb29eac00,276,531.00,448,313.00,584,593.00,405,415.00,51,8.00,343,804.00
2,010e3acd01fb1bb37db745be9,27,16.00,165,18.00,1,2.00,9,38.00,11,277.00,358,121.00
3,01722398f1dd91d629c842eae,35,415.00,168,253.00,834,740.00,800,865.00,26,587.00,7,281.00
4,01d76805a4a4900d37767bcf2,282,189.00,376,309.00,225,152.00,70,303.00,582,93.00,339,301.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,265,169.00,177,94.00,215,51.00,96,493.00,420,271.00,512,465.00
950,feba29952d39a2b39d6b58481,463,543.00,370,785.00,724,309.00,874,624.00,434,524.00,405,547.00
951,fee1881a18aa180338c3fe312,723,562.00,714,575.00,193,551.00,704,446.00,708,187.00,698,675.00
952,ff7db7310ab5270accf0422e1,298,29.00,373,36.00,625,544.00,382,43.00,537,523.00,166,15.00
953,ffedba4233ac1a8729cd5749d,90,22.00,223,28.00,225,37.00,81,584.00,240,29.00,121,72.00

In [154]:
#updated definition of 'stakeholder' to include metadata, i.e table named 'base'
stakeholder = pd.merge(base, stakeholder, how="left", on="company_perm_id")
stakeholder

,company_perm_id,ticker,company_name,description,industry_name,marketcap,WEIGHTED_SCORE_22,WEIGHTED_SCORE_21,COMM_22,COMM_21,CUST_22,CUST_21,ENV_22,ENV_21,SHARE_22,SHARE_21,WORKER_22,WORKER_21
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00",686,613.00,920,811.00,376,242.00,597,315.00,479,858.00,671,446.00
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00",276,531.00,448,313.00,584,593.00,405,415.00,51,8.00,343,804.00
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00",27,16.00,165,18.00,1,2.00,9,38.00,11,277.00,358,121.00
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00",35,415.00,168,253.00,834,740.00,800,865.00,26,587.00,7,281.00
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00",282,189.00,376,309.00,225,152.00,70,303.00,582,93.00,339,301.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00",265,169.00,177,94.00,215,51.00,96,493.00,420,271.00,512,465.00
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00",463,543.00,370,785.00,724,309.00,874,624.00,434,524.00,405,547.00
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00",723,562.00,714,575.00,193,551.00,704,446.00,708,187.00,698,675.00
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00",298,29.00,373,36.00,625,544.00,382,43.00,537,523.00,166,15.00
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00",90,22.00,223,28.00,225,37.00,81,584.00,240,29.00,121,72.00

In [155]:
#Creating columns that are calculations of the change in rankins in each stakeholder + overall from 2021 to 2022
stakeholder['comm_changes'] = stakeholder['COMM_21'] - stakeholder['COMM_22']
stakeholder['cust_changes'] = stakeholder['CUST_21'] - stakeholder['CUST_22']
stakeholder['env_changes'] = stakeholder['ENV_21'] - stakeholder['ENV_22']
stakeholder['share_changes'] = stakeholder['SHARE_21'] - stakeholder['SHARE_22']
stakeholder['worker_changes'] = stakeholder['WORKER_21'] - stakeholder['WORKER_22']
stakeholder['overall_changes'] = stakeholder['WEIGHTED_SCORE_21'] - stakeholder['WEIGHTED_SCORE_22']
stakeholder
#Do we want these columns to be grouped with their respective area?
#ex: COMM_22, COMM_21, comm_changes, CUST_22, CUST_21, etc...
#If so, how would we do that?

,company_perm_id,ticker,company_name,description,industry_name,marketcap,WEIGHTED_SCORE_22,WEIGHTED_SCORE_21,COMM_22,COMM_21,...,SHARE_22,SHARE_21,WORKER_22,WORKER_21,comm_changes,cust_changes,env_changes,share_changes,worker_changes,overall_changes
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00",686,613.00,920,811.00,...,479,858.00,671,446.00,-109.00,-134.00,-282.00,379.00,-225.00,-73.00
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00",276,531.00,448,313.00,...,51,8.00,343,804.00,-135.00,9.00,10.00,-43.00,461.00,255.00
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00",27,16.00,165,18.00,...,11,277.00,358,121.00,-147.00,1.00,29.00,266.00,-237.00,-11.00
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00",35,415.00,168,253.00,...,26,587.00,7,281.00,85.00,-94.00,65.00,561.00,274.00,380.00
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00",282,189.00,376,309.00,...,582,93.00,339,301.00,-67.00,-73.00,233.00,-489.00,-38.00,-93.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00",265,169.00,177,94.00,...,420,271.00,512,465.00,-83.00,-164.00,397.00,-149.00,-47.00,-96.00
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00",463,543.00,370,785.00,...,434,524.00,405,547.00,415.00,-415.00,-250.00,90.00,142.00,80.00
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00",723,562.00,714,575.00,...,708,187.00,698,675.00,-139.00,358.00,-258.00,-521.00,-23.00,-161.00
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00",298,29.00,373,36.00,...,537,523.00,166,15.00,-337.00,-81.00,-339.00,-14.00,-151.00,-269.00
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00",90,22.00,223,28.00,...,240,29.00,121,72.00,-195.00,-188.00,503.00,-211.00,-49.00,-68.00

In [156]:
#Listing column names within 'stakeholder' table
stakeholder.columns

Index(['company_perm_id', 'ticker', 'company_name', 'description',
       'industry_name', 'marketcap', 'WEIGHTED_SCORE_22', 'WEIGHTED_SCORE_21',
       'COMM_22', 'COMM_21', 'CUST_22', 'CUST_21', 'ENV_22', 'ENV_21',
       'SHARE_22', 'SHARE_21', 'WORKER_22', 'WORKER_21', 'comm_changes',
       'cust_changes', 'env_changes', 'share_changes', 'worker_changes',
       'overall_changes'],
      dtype='object')

In [157]:
#Sort/order by ascending order
stakeholder.sort_values(by=['WEIGHTED_SCORE_22'], inplace=True)
stakeholder

,company_perm_id,ticker,company_name,description,industry_name,marketcap,WEIGHTED_SCORE_22,WEIGHTED_SCORE_21,COMM_22,COMM_21,...,SHARE_22,SHARE_21,WORKER_22,WORKER_21,comm_changes,cust_changes,env_changes,share_changes,worker_changes,overall_changes
774,cbe3019e0a1bd5b3158856d49,GOOG,Alphabet Inc,"Alphabet is a collection of businesses, the la...",Internet,"1,909,550,000,000.00",1,5.00,3,5.00,...,108,877.00,10,11.00,2.00,-11.00,-13.00,769.00,1.00,4.00
837,e2d8dba6f3aaf55b908a3ba77,INTC,Intel Corp,Intel designs and manufactures products and te...,Semiconductors & Equipment,"218,672,000,000.00",2,4.00,53,21.00,...,1,23.00,27,9.00,-32.00,-1.00,-14.00,22.00,-18.00,2.00
403,681873205a765c355f58f1911,MSFT,Microsoft Corporation,"Microsoft is a technology company, building co...",Software,"2,275,130,000,000.00",3,1.00,12,6.00,...,199,20.00,12,3.00,-6.00,-66.00,3.00,-179.00,-9.00,-2.00
96,1b6561524cdf643c84f56f4d7,CRM,"Salesforce.com, inc.",Salesforce is a technology company providing c...,Software,"283,930,000,000.00",4,7.00,40,90.00,...,200,123.00,2,2.00,50.00,-12.00,31.00,-77.00,0.00,3.00
907,f427c9aedfd9e2b39a6a347b3,BAC,Bank of America Corporation,Bank of America is a bank and financial holdin...,Banks,"379,260,000,000.00",5,12.00,1,40.00,...,241,426.00,36,7.00,39.00,125.00,-2.00,185.00,-29.00,7.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,a035896360efe56b2f1c3923b,ACHC,Acadia Healthcare Co Inc,Acadian Healthcare acquires and develops behav...,Health Care Providers,"5,006,288,844.00",950,915.00,877,892.00,...,941,874.00,862,840.00,15.00,-55.00,-117.00,-67.00,-22.00,-35.00
770,cb082ccdc2b7614a95e2043c8,AGL,"agilon health, inc.","agilon health, inc. offers healthcare services...",Health Care Equipment & Services,"9,275,643,149.00",951,nan,713,nan,...,883,nan,931,nan,nan,nan,nan,nan,nan,nan
834,e1a9d88bbdaa93f403690d1b6,RH,RH,"RH, together with its subsidiaries, operates a...",Retail,"13,994,401,906.00",952,nan,673,nan,...,854,nan,940,nan,nan,nan,nan,nan,nan,nan
329,510cbc1af1bf2a59ea2a91eb8,OLLI,Ollie's Bargain Outlet Holdings,Ollies Bargain Outlet is a retail company that...,Retail,"4,309,005,262.00",953,784.00,774,657.00,...,620,663.00,949,873.00,-117.00,-341.00,-207.00,43.00,-76.00,-169.00
679,b4dec47e2a3457b5fb37ea077,SKLZ,Skillz Inc.,Skillz Inc. operates a mobile games platform t...,Internet,"3,365,086,525.00",954,nan,831,nan,...,876,nan,913,nan,nan,nan,nan,nan,nan,nan

In [158]:
#Export to Excel file, no additional index (0)
stakeholder.to_excel("stakeholder.xlsx",index = False)
#WILL NEED TO FORMAT COLUMN 'marketcap' AS CURRENCY AFTER DOWNLOAD

In [159]:
#Defining 'issue_ranks' table as everything from 'all_ranks_22' EXCEPT for the columns explicitly named below
issue_ranks = all_ranks_2022.drop(['COMM_22','COMM_21',
                                'CUST_22','CUST_21',
                                'ENV_22','ENV_21',
                                'SHARE_22','SHARE_21',
                                'WORKER_22','WORKER_21',
                                'WEIGHTED_SCORE_21'], axis=1)
issue_ranks

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMMDEV_22,...,PERFORMANCE_21,PHILANTHROPY_21,PRIORITIZATION_21,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00",757,906,499,653,...,416.00,598.00,605.00,122.00,75.00,842.00,304.00,318.00,1.00,481.00
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00",204,441,219,239,...,309.00,719.00,50.00,560.00,318.00,1.00,131.00,495.00,1.00,730.00
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00",372,793,10,18,...,729.00,158.00,229.00,19.00,85.00,345.00,35.00,56.00,1.00,72.00
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00",380,1,863,42,...,901.00,198.00,308.00,560.00,398.00,377.00,602.00,481.00,1.00,321.00
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00",222,217,184,199,...,57.00,347.00,252.00,67.00,398.00,100.00,203.00,565.00,1.00,216.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00",269,527,32,601,...,627.00,107.00,226.00,560.00,6.00,360.00,34.00,858.00,1.00,716.00
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00",405,270,824,653,...,51.00,659.00,580.00,226.00,85.00,628.00,228.00,835.00,1.00,481.00
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00",518,655,727,653,...,377.00,759.00,271.00,365.00,300.00,100.00,304.00,751.00,1.00,716.00
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00",361,345,208,347,...,416.00,20.00,418.00,560.00,54.00,605.00,71.00,41.00,1.00,82.00
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00",90,74,38,1,...,416.00,29.00,66.00,67.00,50.00,1.00,1.00,127.00,1.00,592.00

In [160]:
#Order by 2022 rank
issue_ranks.sort_values(by=['WEIGHTED_SCORE_22'], inplace=True)
issue_ranks

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMMDEV_22,...,PERFORMANCE_21,PHILANTHROPY_21,PRIORITIZATION_21,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21
774,cbe3019e0a1bd5b3158856d49,GOOG,Alphabet Inc,"Alphabet is a collection of businesses, the la...",Internet,"1,909,550,000,000.00",37,144,115,109,...,119.00,36.00,842.00,1.00,173.00,851.00,54.00,28.00,888.00,9.00
837,e2d8dba6f3aaf55b908a3ba77,INTC,Intel Corp,Intel designs and manufactures products and te...,Semiconductors & Equipment,"218,672,000,000.00",12,86,283,1,...,165.00,40.00,129.00,19.00,85.00,1.00,1.00,1.00,1.00,47.00
403,681873205a765c355f58f1911,MSFT,Microsoft Corporation,"Microsoft is a technology company, building co...",Software,"2,275,130,000,000.00",3,203,8,18,...,73.00,32.00,66.00,1.00,236.00,100.00,28.00,1.00,1.00,4.00
96,1b6561524cdf643c84f56f4d7,CRM,"Salesforce.com, inc.",Salesforce is a technology company providing c...,Software,"283,930,000,000.00",2,136,17,109,...,92.00,1.00,418.00,226.00,236.00,93.00,108.00,51.00,1.00,3.00
907,f427c9aedfd9e2b39a6a347b3,BAC,Bank of America Corporation,Bank of America is a bank and financial holdin...,Banks,"379,260,000,000.00",46,315,100,95,...,416.00,16.00,19.00,67.00,356.00,781.00,88.00,1.00,894.00,64.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,a035896360efe56b2f1c3923b,ACHC,Acadia Healthcare Co Inc,Acadian Healthcare acquires and develops behav...,Health Care Providers,"5,006,288,844.00",939,944,644,653,...,566.00,659.00,778.00,732.00,923.00,833.00,924.00,403.00,1.00,863.00
770,cb082ccdc2b7614a95e2043c8,AGL,"agilon health, inc.","agilon health, inc. offers healthcare services...",Health Care Equipment & Services,"9,275,643,149.00",731,941,743,387,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
834,e1a9d88bbdaa93f403690d1b6,RH,RH,"RH, together with its subsidiaries, operates a...",Retail,"13,994,401,906.00",953,895,854,653,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
329,510cbc1af1bf2a59ea2a91eb8,OLLI,Ollie's Bargain Outlet Holdings,Ollies Bargain Outlet is a retail company that...,Retail,"4,309,005,262.00",950,917,894,653,...,228.00,540.00,773.00,226.00,398.00,628.00,602.00,858.00,1.00,902.00
679,b4dec47e2a3457b5fb37ea077,SKLZ,Skillz Inc.,Skillz Inc. operates a mobile games platform t...,Internet,"3,365,086,525.00",531,713,903,653,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [161]:
#Listing column names within 'issue_ranks' table
issue_ranks.columns

Index(['company_perm_id', 'ticker', 'company_name', 'description',
       'industry_name', 'marketcap', 'BENEFITS_22', 'CAREER_22',
       'CLIMATECHANGE_22', 'COMMDEV_22', 'DEI_22', 'EXPERIENCE_22',
       'HEALTH_22', 'JOBS_22', 'PERFORMANCE_22', 'PHILANTHROPY_22',
       'POLLUTION_22', 'PRIORITIZATION_22', 'PRIVACY_22', 'PRODHARM_22',
       'RESOURCES_22', 'RESPONSIBLE_22', 'SUPPLY_CHAIN_22',
       'SUSTPRODUCTSERVICE_22', 'TRANSPARENT_22', 'WAGES_22',
       'WEIGHTED_SCORE_22', 'BENEFITS_21', 'CAREER_21', 'CLIMATECHANGE_21',
       'COMMDEV_21', 'DEI_21', 'ENVEFFICIENT_21', 'EXPERIENCE_21', 'HEALTH_21',
       'JOBS_21', 'PERFORMANCE_21', 'PHILANTHROPY_21', 'PRIORITIZATION_21',
       'PRIVACY_21', 'PRODHARM_21', 'RESPONSIBLE_21', 'SUPPLY_CHAIN_21',
       'SUSTPRODUCTSERVICE_21', 'TRANSPARENT_21', 'WAGES_21'],
      dtype='object')

In [162]:
#Creating columns that are changes in Issue rankings from 2021 to 2022 and adding them to the 'issue_ranks' table
issue_ranks['benefits_changes'] = issue_ranks['BENEFITS_21'] - issue_ranks['BENEFITS_22']
issue_ranks['career_changes'] = issue_ranks['CAREER_21'] - issue_ranks['CAREER_22']

issue_ranks['climatechange_changes'] = issue_ranks['CLIMATECHANGE_21'] - issue_ranks['CLIMATECHANGE_22']
issue_ranks['commdev_changes'] = issue_ranks['COMMDEV_21'] - issue_ranks['COMMDEV_22']
issue_ranks['dei_changes'] = issue_ranks['DEI_21'] - issue_ranks['DEI_22']
issue_ranks['experience_changes'] = issue_ranks['EXPERIENCE_21'] - issue_ranks['EXPERIENCE_22']

issue_ranks['health_changes'] = issue_ranks['HEALTH_21'] - issue_ranks['HEALTH_22']
issue_ranks['jobs_changes'] = issue_ranks['JOBS_21'] - issue_ranks['JOBS_22']
issue_ranks['performance_changes'] = issue_ranks['PERFORMANCE_21'] - issue_ranks['PERFORMANCE_22']
issue_ranks['philanthropy_changes'] = issue_ranks['PHILANTHROPY_21'] - issue_ranks['PHILANTHROPY_22']

issue_ranks['prioritization_changes'] = issue_ranks['PRIORITIZATION_21'] - issue_ranks['PRIORITIZATION_22']
issue_ranks['privacy_changes'] = issue_ranks['PRIVACY_21'] - issue_ranks['PRIVACY_22']
issue_ranks['prodharm_changes'] = issue_ranks['PRODHARM_21'] - issue_ranks['PRODHARM_22']


issue_ranks['responsible_changes'] = issue_ranks['RESPONSIBLE_21'] - issue_ranks['RESPONSIBLE_22']
issue_ranks['supply_chain_changes'] = issue_ranks['SUPPLY_CHAIN_21'] - issue_ranks['SUPPLY_CHAIN_22']

issue_ranks['sustproductservice_changes'] = issue_ranks['SUSTPRODUCTSERVICE_21'] - issue_ranks['SUSTPRODUCTSERVICE_22']
issue_ranks['transparent_changes'] = issue_ranks['TRANSPARENT_21'] - issue_ranks['TRANSPARENT_22']
issue_ranks['wages_changes'] = issue_ranks['WAGES_21'] - issue_ranks['WAGES_22']

issue_ranks['pollutionresources_proxy'] = issue_ranks['ENVEFFICIENT_21'] - (
                                                ((issue_ranks['POLLUTION_22']*2.605042) +
                                                (issue_ranks['RESOURCES_22']*1.630986)) /
                                                (2.605042 + 1.630986)
)

issue_ranks

#POLLUTION and RESOURCES are unique to 2022.
#The previous singular issue - instead of those two - was ENVEFFICIENT
#This value is a proxy. IT IS NOT REFLECTIVE OF RANK CHANGES
#The proxy looks at the 'weighted average' of the 2022 issue ranks, multiplied by their weight.
#It is based on cell K46/47 here -> https://docs.google.com/spreadsheets/d/1QrrbxRiOY_dBSiqSyo4RkOP15lHytZOQPJKKyvVnyaI/edit?pli=1#gid=1652388635

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMMDEV_22,...,philanthropy_changes,prioritization_changes,privacy_changes,prodharm_changes,responsible_changes,supply_chain_changes,sustproductservice_changes,transparent_changes,wages_changes,pollutionresources_proxy
774,cbe3019e0a1bd5b3158856d49,GOOG,Alphabet Inc,"Alphabet is a collection of businesses, the la...",Internet,"1,909,550,000,000.00",37,144,115,109,...,-19.00,580.00,0.00,-61.00,756.00,9.00,27.00,-34.00,-4.00,-39.01
837,e2d8dba6f3aaf55b908a3ba77,INTC,Intel Corp,Intel designs and manufactures products and te...,Semiconductors & Equipment,"218,672,000,000.00",12,86,283,1,...,-185.00,122.00,-18.00,83.00,-82.00,0.00,0.00,0.00,-186.00,-17.27
403,681873205a765c355f58f1911,MSFT,Microsoft Corporation,"Microsoft is a technology company, building co...",Software,"2,275,130,000,000.00",3,203,8,18,...,-497.00,-85.00,-133.00,-117.00,-590.00,-93.00,0.00,0.00,-76.00,-10.64
96,1b6561524cdf643c84f56f4d7,CRM,"Salesforce.com, inc.",Salesforce is a technology company providing c...,Software,"283,930,000,000.00",2,136,17,109,...,0.00,34.00,92.00,-49.00,-3.00,-81.00,50.00,0.00,-13.00,-72.45
907,f427c9aedfd9e2b39a6a347b3,BAC,Bank of America Corporation,Bank of America is a bank and financial holdin...,Banks,"379,260,000,000.00",46,315,100,95,...,-9.00,-143.00,58.00,-168.00,90.00,55.00,0.00,-29.00,-246.00,230.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,a035896360efe56b2f1c3923b,ACHC,Acadia Healthcare Co Inc,Acadian Healthcare acquires and develops behav...,Health Care Providers,"5,006,288,844.00",939,944,644,653,...,-106.00,-84.00,-171.00,-10.00,-81.00,167.00,-35.00,0.00,92.00,-159.80
770,cb082ccdc2b7614a95e2043c8,AGL,"agilon health, inc.","agilon health, inc. offers healthcare services...",Health Care Equipment & Services,"9,275,643,149.00",731,941,743,387,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
834,e1a9d88bbdaa93f403690d1b6,RH,RH,"RH, together with its subsidiaries, operates a...",Retail,"13,994,401,906.00",953,895,854,653,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
329,510cbc1af1bf2a59ea2a91eb8,OLLI,Ollie's Bargain Outlet Holdings,Ollies Bargain Outlet is a retail company that...,Retail,"4,309,005,262.00",950,917,894,653,...,-225.00,-86.00,-165.00,-129.00,627.00,-155.00,420.00,0.00,-45.00,-592.39
679,b4dec47e2a3457b5fb37ea077,SKLZ,Skillz Inc.,Skillz Inc. operates a mobile games platform t...,Internet,"3,365,086,525.00",531,713,903,653,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [163]:
#Setting the Index as the rank in 2022
issue_ranks.set_index('WEIGHTED_SCORE_22')
issue_ranks
#Doesn't seem to do anything about the location of the column 'WEIGHTED_SCORE_22'
#Could I have done this^ in place of sort_values??? Would it have sorted them?

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMMDEV_22,...,philanthropy_changes,prioritization_changes,privacy_changes,prodharm_changes,responsible_changes,supply_chain_changes,sustproductservice_changes,transparent_changes,wages_changes,pollutionresources_proxy
774,cbe3019e0a1bd5b3158856d49,GOOG,Alphabet Inc,"Alphabet is a collection of businesses, the la...",Internet,"1,909,550,000,000.00",37,144,115,109,...,-19.00,580.00,0.00,-61.00,756.00,9.00,27.00,-34.00,-4.00,-39.01
837,e2d8dba6f3aaf55b908a3ba77,INTC,Intel Corp,Intel designs and manufactures products and te...,Semiconductors & Equipment,"218,672,000,000.00",12,86,283,1,...,-185.00,122.00,-18.00,83.00,-82.00,0.00,0.00,0.00,-186.00,-17.27
403,681873205a765c355f58f1911,MSFT,Microsoft Corporation,"Microsoft is a technology company, building co...",Software,"2,275,130,000,000.00",3,203,8,18,...,-497.00,-85.00,-133.00,-117.00,-590.00,-93.00,0.00,0.00,-76.00,-10.64
96,1b6561524cdf643c84f56f4d7,CRM,"Salesforce.com, inc.",Salesforce is a technology company providing c...,Software,"283,930,000,000.00",2,136,17,109,...,0.00,34.00,92.00,-49.00,-3.00,-81.00,50.00,0.00,-13.00,-72.45
907,f427c9aedfd9e2b39a6a347b3,BAC,Bank of America Corporation,Bank of America is a bank and financial holdin...,Banks,"379,260,000,000.00",46,315,100,95,...,-9.00,-143.00,58.00,-168.00,90.00,55.00,0.00,-29.00,-246.00,230.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,a035896360efe56b2f1c3923b,ACHC,Acadia Healthcare Co Inc,Acadian Healthcare acquires and develops behav...,Health Care Providers,"5,006,288,844.00",939,944,644,653,...,-106.00,-84.00,-171.00,-10.00,-81.00,167.00,-35.00,0.00,92.00,-159.80
770,cb082ccdc2b7614a95e2043c8,AGL,"agilon health, inc.","agilon health, inc. offers healthcare services...",Health Care Equipment & Services,"9,275,643,149.00",731,941,743,387,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
834,e1a9d88bbdaa93f403690d1b6,RH,RH,"RH, together with its subsidiaries, operates a...",Retail,"13,994,401,906.00",953,895,854,653,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
329,510cbc1af1bf2a59ea2a91eb8,OLLI,Ollie's Bargain Outlet Holdings,Ollies Bargain Outlet is a retail company that...,Retail,"4,309,005,262.00",950,917,894,653,...,-225.00,-86.00,-165.00,-129.00,627.00,-155.00,420.00,0.00,-45.00,-592.39
679,b4dec47e2a3457b5fb37ea077,SKLZ,Skillz Inc.,Skillz Inc. operates a mobile games platform t...,Internet,"3,365,086,525.00",531,713,903,653,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [164]:
#Exporting to Excel
issue_ranks.to_excel("issue_ranks.xlsx",index = False)
#Moved weighted score to column A after exporting
#Converted marketcap to currency

In [165]:
#Taking original raw 2022 data and creating a separate industry_rankings table
#Had previously pivoted and excluded industry_rank in favor of overall_rank
#Pivoting to index by company_perm_id, makes slugs columns
industry_rankings_2022_pivot = rankings_2022_raw.pivot(index ='company_perm_id',
                                                    columns ='model_slug',
                                                    values ='industry_rank')
industry_rankings_2022_pivot

model_slug,BENEFITS,CAREER,CLIMATECHANGE,COMM,COMMDEV,CUST,DEI,ENV,EXPERIENCE,HEALTH,...,PRODHARM,RESOURCES,RESPONSIBLE,SHARE,SUPPLY_CHAIN,SUSTPRODUCTSERVICE,TRANSPARENT,WAGES,WEIGHTED_SCORE,WORKER
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,40,53,18,54,34,26,15,26,4,6,...,35,16,51,23,27,9,1,30,30,30
00dae748aa57b455fb29eac00,7,6,6,7,5,12,11,7,7,4,...,2,9,1,1,3,7,1,8,5,8
010e3acd01fb1bb37db745be9,11,19,2,4,1,1,2,2,3,5,...,1,9,13,1,4,2,1,18,3,13
01722398f1dd91d629c842eae,5,1,9,4,1,7,2,11,2,1,...,2,8,6,1,6,10,1,1,1,1
01d76805a4a4900d37767bcf2,14,14,8,24,7,9,17,7,13,15,...,10,30,8,29,3,1,1,17,17,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,8,27,2,20,31,29,2,7,25,6,...,6,9,26,22,6,13,1,34,11,9
feba29952d39a2b39d6b58481,16,16,25,9,26,27,18,24,4,10,...,2,26,7,20,10,23,1,29,19,20
fee1881a18aa180338c3fe312,27,31,38,35,34,6,26,39,4,6,...,2,38,28,42,6,12,1,48,35,35
ff7db7310ab5270accf0422e1,17,9,4,13,11,45,4,14,4,1,...,37,18,49,29,2,11,1,13,7,5
ffedba4233ac1a8729cd5749d,2,4,1,7,1,2,1,1,5,21,...,2,12,2,10,2,2,1,18,2,7

In [166]:
#Adding a suffix to all columns in this table. That way, we know which year it refers to
industry_rankings_2022_pivot = industry_rankings_2022_pivot.add_suffix('_22')
industry_rankings_2022_pivot

model_slug,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,COMMDEV_22,CUST_22,DEI_22,ENV_22,EXPERIENCE_22,HEALTH_22,...,PRODHARM_22,RESOURCES_22,RESPONSIBLE_22,SHARE_22,SUPPLY_CHAIN_22,SUSTPRODUCTSERVICE_22,TRANSPARENT_22,WAGES_22,WEIGHTED_SCORE_22,WORKER_22
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,40,53,18,54,34,26,15,26,4,6,...,35,16,51,23,27,9,1,30,30,30
00dae748aa57b455fb29eac00,7,6,6,7,5,12,11,7,7,4,...,2,9,1,1,3,7,1,8,5,8
010e3acd01fb1bb37db745be9,11,19,2,4,1,1,2,2,3,5,...,1,9,13,1,4,2,1,18,3,13
01722398f1dd91d629c842eae,5,1,9,4,1,7,2,11,2,1,...,2,8,6,1,6,10,1,1,1,1
01d76805a4a4900d37767bcf2,14,14,8,24,7,9,17,7,13,15,...,10,30,8,29,3,1,1,17,17,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,8,27,2,20,31,29,2,7,25,6,...,6,9,26,22,6,13,1,34,11,9
feba29952d39a2b39d6b58481,16,16,25,9,26,27,18,24,4,10,...,2,26,7,20,10,23,1,29,19,20
fee1881a18aa180338c3fe312,27,31,38,35,34,6,26,39,4,6,...,2,38,28,42,6,12,1,48,35,35
ff7db7310ab5270accf0422e1,17,9,4,13,11,45,4,14,4,1,...,37,18,49,29,2,11,1,13,7,5
ffedba4233ac1a8729cd5749d,2,4,1,7,1,2,1,1,5,21,...,2,12,2,10,2,2,1,18,2,7

In [167]:
#Getting industry rankings from 2021
industry_rankings_2021_raw = jc_api.get_data("apim_ss_ft_models_for_companies_2021_forbes",
                               ["fields=company_perm_id, model_slug, value, value_type",
                                "value_type=in:'industry_rank'"])
industry_rankings_2021_raw

                 company_perm_id      model_slug  value     value_type
0      0040f5f17ffc61944024e975e           WAGES     10  industry_rank
1      00aa86290f0973a72bca4ef3b           WAGES     13  industry_rank
2      00dae748aa57b455fb29eac00           WAGES     22  industry_rank
3      00fb5c9ebbdc6c359d2e001c6           WAGES      3  industry_rank
4      010e3acd01fb1bb37db745be9           WAGES      5  industry_rank
...                          ...             ...    ...            ...
23195  fe9668a59a7386ac1e898d980  WEIGHTED_SCORE     11  industry_rank
23196  feba29952d39a2b39d6b58481  WEIGHTED_SCORE     22  industry_rank
23197  fee1881a18aa180338c3fe312  WEIGHTED_SCORE     21  industry_rank
23198  ff7db7310ab5270accf0422e1  WEIGHTED_SCORE      1  industry_rank
23199  ffedba4233ac1a8729cd5749d  WEIGHTED_SCORE      1  industry_rank

[23200 rows x 4 columns]

In [168]:
#Pivot to index by company_perm_id
#Taking original raw 2022 data and creating a separate industry_rankings table
#Had previously pivoted and excluded industry_rank in favor of overall_rank
#Pivoting to index by company_perm_id, makes slugs columns
industry_rankings_2021_pivot = industry_rankings_2021_raw.pivot(index ='company_perm_id',
                                                    columns ='model_slug',
                                                    values ='value')
industry_rankings_2021_pivot

model_slug,BENEFITS,CAREER,CLIMATECHANGE,COMM,COMMDEV,CUST,DEI,ENV,ENVEFFICIENT,EXPERIENCE,...,PRIVACY,PRODHARM,RESPONSIBLE,SHARE,SUPPLY_CHAIN,SUSTPRODUCTSERVICE,TRANSPARENT,WAGES,WEIGHTED_SCORE,WORKER
company_perm_id,,,,,,,,,,,,,,,,,,,,,
0040f5f17ffc61944024e975e,13,22,7,4,9,18,10,15,13,23,...,14,8,24,21,3,12,1,10,13,17
00aa86290f0973a72bca4ef3b,13,23,3,29,25,8,16,10,4,19,...,3,2,37,37,21,13,1,13,23,15
00dae748aa57b455fb29eac00,17,20,1,6,8,15,9,25,2,17,...,15,2,1,1,4,25,1,22,13,19
00fb5c9ebbdc6c359d2e001c6,26,6,1,9,13,16,12,15,4,10,...,10,23,2,15,8,14,1,3,8,6
010e3acd01fb1bb37db745be9,10,16,2,3,3,2,2,3,2,1,...,2,4,8,2,3,3,1,5,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,24,27,9,10,38,6,5,25,6,7,...,27,1,15,15,2,24,1,23,11,17
feba29952d39a2b39d6b58481,19,14,11,23,14,9,14,18,12,12,...,8,6,22,21,14,20,1,23,22,23
fee1881a18aa180338c3fe312,27,36,9,19,21,28,12,18,8,23,...,19,23,2,6,12,14,1,24,21,19
ff7db7310ab5270accf0422e1,2,7,1,1,11,27,3,1,32,31,...,29,12,23,21,4,2,1,2,1,1
ffedba4233ac1a8729cd5749d,2,11,3,1,2,1,2,4,7,1,...,2,1,1,1,1,4,1,22,1,2

In [169]:
#Suffix with columns_21
#Adding a suffix to all columns in this table. That way, we know which year it refers to
industry_rankings_2021_pivot = industry_rankings_2021_pivot.add_suffix('_21')
industry_rankings_2021_pivot

model_slug,BENEFITS_21,CAREER_21,CLIMATECHANGE_21,COMM_21,COMMDEV_21,CUST_21,DEI_21,ENV_21,ENVEFFICIENT_21,EXPERIENCE_21,...,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SHARE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21,WEIGHTED_SCORE_21,WORKER_21
company_perm_id,,,,,,,,,,,,,,,,,,,,,
0040f5f17ffc61944024e975e,13,22,7,4,9,18,10,15,13,23,...,14,8,24,21,3,12,1,10,13,17
00aa86290f0973a72bca4ef3b,13,23,3,29,25,8,16,10,4,19,...,3,2,37,37,21,13,1,13,23,15
00dae748aa57b455fb29eac00,17,20,1,6,8,15,9,25,2,17,...,15,2,1,1,4,25,1,22,13,19
00fb5c9ebbdc6c359d2e001c6,26,6,1,9,13,16,12,15,4,10,...,10,23,2,15,8,14,1,3,8,6
010e3acd01fb1bb37db745be9,10,16,2,3,3,2,2,3,2,1,...,2,4,8,2,3,3,1,5,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,24,27,9,10,38,6,5,25,6,7,...,27,1,15,15,2,24,1,23,11,17
feba29952d39a2b39d6b58481,19,14,11,23,14,9,14,18,12,12,...,8,6,22,21,14,20,1,23,22,23
fee1881a18aa180338c3fe312,27,36,9,19,21,28,12,18,8,23,...,19,23,2,6,12,14,1,24,21,19
ff7db7310ab5270accf0422e1,2,7,1,1,11,27,3,1,32,31,...,29,12,23,21,4,2,1,2,1,1
ffedba4233ac1a8729cd5749d,2,11,3,1,2,1,2,4,7,1,...,2,1,1,1,1,4,1,22,1,2

In [170]:
#merge onto 'industry_rankings_2022_pivot'
industry_rankings_2022_pivot = pd.merge(industry_rankings_2022_pivot, industry_rankings_2021_pivot, how="left", on="company_perm_id")
industry_rankings_2022_pivot

model_slug,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,COMMDEV_22,CUST_22,DEI_22,ENV_22,EXPERIENCE_22,HEALTH_22,...,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SHARE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21,WEIGHTED_SCORE_21,WORKER_21
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,40,53,18,54,34,26,15,26,4,6,...,3.00,2.00,37.00,37.00,21.00,13.00,1.00,13.00,23.00,15.00
00dae748aa57b455fb29eac00,7,6,6,7,5,12,11,7,7,4,...,15.00,2.00,1.00,1.00,4.00,25.00,1.00,22.00,13.00,19.00
010e3acd01fb1bb37db745be9,11,19,2,4,1,1,2,2,3,5,...,2.00,4.00,8.00,2.00,3.00,3.00,1.00,5.00,3.00,6.00
01722398f1dd91d629c842eae,5,1,9,4,1,7,2,11,2,1,...,8.00,2.00,17.00,20.00,14.00,12.00,1.00,13.00,12.00,11.00
01d76805a4a4900d37767bcf2,14,14,8,24,7,9,17,7,13,15,...,3.00,3.00,9.00,5.00,7.00,11.00,1.00,11.00,7.00,9.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,8,27,2,20,31,29,2,7,25,6,...,27.00,1.00,15.00,15.00,2.00,24.00,1.00,23.00,11.00,17.00
feba29952d39a2b39d6b58481,16,16,25,9,26,27,18,24,4,10,...,8.00,6.00,22.00,21.00,14.00,20.00,1.00,23.00,22.00,23.00
fee1881a18aa180338c3fe312,27,31,38,35,34,6,26,39,4,6,...,19.00,23.00,2.00,6.00,12.00,14.00,1.00,24.00,21.00,19.00
ff7db7310ab5270accf0422e1,17,9,4,13,11,45,4,14,4,1,...,29.00,12.00,23.00,21.00,4.00,2.00,1.00,2.00,1.00,1.00
ffedba4233ac1a8729cd5749d,2,4,1,7,1,2,1,1,5,21,...,2.00,1.00,1.00,1.00,1.00,4.00,1.00,22.00,1.00,2.00

In [171]:
#updated name of table and included metadata, i.e table named 'base'
industry_rankings_2022 = pd.merge(base, industry_rankings_2022_pivot, how="left", on="company_perm_id")
industry_rankings_2022

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,...,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SHARE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21,WEIGHTED_SCORE_21,WORKER_21
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00",40,53,18,54,...,3.00,2.00,37.00,37.00,21.00,13.00,1.00,13.00,23.00,15.00
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00",7,6,6,7,...,15.00,2.00,1.00,1.00,4.00,25.00,1.00,22.00,13.00,19.00
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00",11,19,2,4,...,2.00,4.00,8.00,2.00,3.00,3.00,1.00,5.00,3.00,6.00
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00",5,1,9,4,...,8.00,2.00,17.00,20.00,14.00,12.00,1.00,13.00,12.00,11.00
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00",14,14,8,24,...,3.00,3.00,9.00,5.00,7.00,11.00,1.00,11.00,7.00,9.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00",8,27,2,20,...,27.00,1.00,15.00,15.00,2.00,24.00,1.00,23.00,11.00,17.00
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00",16,16,25,9,...,8.00,6.00,22.00,21.00,14.00,20.00,1.00,23.00,22.00,23.00
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00",27,31,38,35,...,19.00,23.00,2.00,6.00,12.00,14.00,1.00,24.00,21.00,19.00
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00",17,9,4,13,...,29.00,12.00,23.00,21.00,4.00,2.00,1.00,2.00,1.00,1.00
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00",2,4,1,7,...,2.00,1.00,1.00,1.00,1.00,4.00,1.00,22.00,1.00,2.00

In [172]:
#Sorting by industry_name first, then current overall score within industry for 2022
industry_rankings_2022.sort_values(by=['industry_name','WEIGHTED_SCORE_22'], inplace=True)
industry_rankings_2022

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,...,PRIVACY_21,PRODHARM_21,RESPONSIBLE_21,SHARE_21,SUPPLY_CHAIN_21,SUSTPRODUCTSERVICE_21,TRANSPARENT_21,WAGES_21,WEIGHTED_SCORE_21,WORKER_21
656,af66b6de5c616f39fba9361d6,LMT,Lockheed Martin Corp,Lockheed Martin is a global security and aeros...,Aerospace & Defense,"100,263,000,000.00",4,1,2,3,...,3.00,7.00,2.00,1.00,1.00,2.00,1.00,1.00,1.00,1.00
693,b7f5ad4cce9d991bfe96e1872,NOC,Northrop Grumman Corporation,Northrop Grumman is a global security company ...,Aerospace & Defense,"62,432,943,624.00",2,4,8,1,...,5.00,5.00,10.00,2.00,2.00,8.00,18.00,3.00,3.00,5.00
899,f24ae0e655f66a765f4580185,RTX,Raytheon Technologies Corp,"Raytheon Technologies Corporation, an aerospac...",Aerospace & Defense,"134,457,000,000.00",3,7,4,2,...,5.00,4.00,11.00,13.00,9.00,7.00,1.00,5.00,2.00,2.00
117,208b13449a1ba16d7e37b4461,TXT,Textron Inc,Textron is a global multi-industry company wit...,Aerospace & Defense,"16,400,174,753.00",9,5,5,5,...,3.00,6.00,5.00,9.00,11.00,9.00,1.00,14.00,10.00,12.00
227,384a205d8d92a3682a6f035ae,LHX,L3 Harris Technologies,L3Harris Technologies is a technology company ...,Aerospace & Defense,"47,557,339,562.00",6,2,3,13,...,19.00,12.00,14.00,10.00,10.00,10.00,1.00,10.00,12.00,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,3125cb2fe964e26e3e57fca5e,NFG,National Fuel Gas Co,National Fuel Gas is a holding company with su...,Utilities,"5,242,916,355.00",35,31,20,33,...,24.00,32.00,5.00,29.00,26.00,32.00,1.00,33.00,35.00,33.00
821,daf9afcb9ddd4f0770218af60,RUN,Sunrun Inc.,"Sunrun Inc. engages in the design, development...",Utilities,"10,175,145,133.00",12,21,31,16,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
83,18f31b6b4619dacaaf2194cd5,EVRG,"Evergy, Inc.",Evergy and its subsidiaries provides energy ge...,Utilities,"14,592,514,283.00",26,23,30,38,...,16.00,13.00,5.00,19.00,26.00,11.00,1.00,36.00,34.00,34.00
425,6e5b1fc2e9811d2cb80e1833c,PCG,PG&E Corporation,PG&E is the holding company for Pacific Gas an...,Utilities,"26,526,689,191.00",2,11,17,9,...,34.00,7.00,36.00,36.00,14.00,16.00,1.00,1.00,20.00,10.00
706,ba7b6cf8e6a0bdcb750038aef,ATO,Atmos Energy Corp,Atmos Energy distributes natural gas through r...,Utilities,"12,286,488,973.00",29,4,35,34,...,16.00,32.00,27.00,34.00,26.00,32.00,1.00,23.00,30.00,17.00

In [173]:
#View column names
industry_rankings_2022.columns

Index(['company_perm_id', 'ticker', 'company_name', 'description',
       'industry_name', 'marketcap', 'BENEFITS_22', 'CAREER_22',
       'CLIMATECHANGE_22', 'COMM_22', 'COMMDEV_22', 'CUST_22', 'DEI_22',
       'ENV_22', 'EXPERIENCE_22', 'HEALTH_22', 'JOBS_22', 'PERFORMANCE_22',
       'PHILANTHROPY_22', 'POLLUTION_22', 'PRIORITIZATION_22', 'PRIVACY_22',
       'PRODHARM_22', 'RESOURCES_22', 'RESPONSIBLE_22', 'SHARE_22',
       'SUPPLY_CHAIN_22', 'SUSTPRODUCTSERVICE_22', 'TRANSPARENT_22',
       'WAGES_22', 'WEIGHTED_SCORE_22', 'WORKER_22', 'BENEFITS_21',
       'CAREER_21', 'CLIMATECHANGE_21', 'COMM_21', 'COMMDEV_21', 'CUST_21',
       'DEI_21', 'ENV_21', 'ENVEFFICIENT_21', 'EXPERIENCE_21', 'HEALTH_21',
       'JOBS_21', 'PERFORMANCE_21', 'PHILANTHROPY_21', 'PRIORITIZATION_21',
       'PRIVACY_21', 'PRODHARM_21', 'RESPONSIBLE_21', 'SHARE_21',
       'SUPPLY_CHAIN_21', 'SUSTPRODUCTSERVICE_21', 'TRANSPARENT_21',
       'WAGES_21', 'WEIGHTED_SCORE_21', 'WORKER_21'],
      dtype='object')

In [174]:
#IN PROCESS

#Calculate changes and insert as new columns

#Creating columns that are changes in Issue rankings from 2021 to 2022 and adding them to the 'issue_ranks' table
industry_rankings_2022['comm_changes'] = industry_rankings_2022['COMM_21'] - industry_rankings_2022['COMM_22']
industry_rankings_2022['cust_changes'] = industry_rankings_2022['CUST_21'] - industry_rankings_2022['CUST_22']
industry_rankings_2022['env_changes'] = industry_rankings_2022['ENV_21'] - industry_rankings_2022['ENV_22']
industry_rankings_2022['share_changes'] = industry_rankings_2022['SHARE_21'] - industry_rankings_2022['SHARE_22']
industry_rankings_2022['worker_changes'] = industry_rankings_2022['WORKER_21'] - industry_rankings_2022['WORKER_22']
industry_rankings_2022['overall_changes'] = industry_rankings_2022['WEIGHTED_SCORE_21'] - industry_rankings_2022['WEIGHTED_SCORE_22']

industry_rankings_2022['benefits_changes'] = industry_rankings_2022['BENEFITS_21'] - industry_rankings_2022['BENEFITS_22']
industry_rankings_2022['career_changes'] = industry_rankings_2022['CAREER_21'] - industry_rankings_2022['CAREER_22']

industry_rankings_2022['climatechange_changes'] = industry_rankings_2022['CLIMATECHANGE_21'] - industry_rankings_2022['CLIMATECHANGE_22']
industry_rankings_2022['commdev_changes'] = industry_rankings_2022['COMMDEV_21'] - industry_rankings_2022['COMMDEV_22']
industry_rankings_2022['dei_changes'] = industry_rankings_2022['DEI_21'] - industry_rankings_2022['DEI_22']
industry_rankings_2022['experience_changes'] = industry_rankings_2022['EXPERIENCE_21'] - industry_rankings_2022['EXPERIENCE_22']

industry_rankings_2022['health_changes'] = industry_rankings_2022['HEALTH_21'] - industry_rankings_2022['HEALTH_22']
industry_rankings_2022['jobs_changes'] = industry_rankings_2022['JOBS_21'] - industry_rankings_2022['JOBS_22']
industry_rankings_2022['performance_changes'] = industry_rankings_2022['PERFORMANCE_21'] - industry_rankings_2022['PERFORMANCE_22']
industry_rankings_2022['philanthropy_changes'] = industry_rankings_2022['PHILANTHROPY_21'] - industry_rankings_2022['PHILANTHROPY_22']

industry_rankings_2022['prioritization_changes'] = industry_rankings_2022['PRIORITIZATION_21'] - industry_rankings_2022['PRIORITIZATION_22']
industry_rankings_2022['privacy_changes'] = industry_rankings_2022['PRIVACY_21'] - industry_rankings_2022['PRIVACY_22']
industry_rankings_2022['prodharm_changes'] = industry_rankings_2022['PRODHARM_21'] - industry_rankings_2022['PRODHARM_22']


industry_rankings_2022['responsible_changes'] = industry_rankings_2022['RESPONSIBLE_21'] - industry_rankings_2022['RESPONSIBLE_22']
industry_rankings_2022['supply_chain_changes'] = industry_rankings_2022['SUPPLY_CHAIN_21'] - industry_rankings_2022['SUPPLY_CHAIN_22']

industry_rankings_2022['sustproductservice_changes'] = industry_rankings_2022['SUSTPRODUCTSERVICE_21'] - industry_rankings_2022['SUSTPRODUCTSERVICE_22']
industry_rankings_2022['transparent_changes'] = industry_rankings_2022['TRANSPARENT_21'] - industry_rankings_2022['TRANSPARENT_22']
industry_rankings_2022['wages_changes'] = industry_rankings_2022['WAGES_21'] - industry_rankings_2022['WAGES_22']

industry_rankings_2022['pollutionresources_proxy'] = industry_rankings_2022['ENVEFFICIENT_21'] - (
                                                ((industry_rankings_2022['POLLUTION_22']*2.605042) +
                                                (industry_rankings_2022['RESOURCES_22']*1.630986)) /
                                                (2.605042 + 1.630986)
)

industry_rankings_2022

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMM_22,...,philanthropy_changes,prioritization_changes,privacy_changes,prodharm_changes,responsible_changes,supply_chain_changes,sustproductservice_changes,transparent_changes,wages_changes,pollutionresources_proxy
656,af66b6de5c616f39fba9361d6,LMT,Lockheed Martin Corp,Lockheed Martin is a global security and aeros...,Aerospace & Defense,"100,263,000,000.00",4,1,2,3,...,-2.00,-1.00,-1.00,-1.00,-4.00,-4.00,1.00,0.00,-2.00,-2.08
693,b7f5ad4cce9d991bfe96e1872,NOC,Northrop Grumman Corporation,Northrop Grumman is a global security company ...,Aerospace & Defense,"62,432,943,624.00",2,4,8,1,...,1.00,-2.00,-8.00,-3.00,3.00,1.00,6.00,1.00,-1.00,-1.23
899,f24ae0e655f66a765f4580185,RTX,Raytheon Technologies Corp,"Raytheon Technologies Corporation, an aerospac...",Aerospace & Defense,"134,457,000,000.00",3,7,4,2,...,4.00,5.00,1.00,2.00,7.00,6.00,3.00,0.00,-3.00,-1.39
117,208b13449a1ba16d7e37b4461,TXT,Textron Inc,Textron is a global multi-industry company wit...,Aerospace & Defense,"16,400,174,753.00",9,5,5,5,...,0.00,2.00,1.00,-2.00,4.00,-1.00,0.00,0.00,3.00,11.47
227,384a205d8d92a3682a6f035ae,LHX,L3 Harris Technologies,L3Harris Technologies is a technology company ...,Aerospace & Defense,"47,557,339,562.00",6,2,3,13,...,-1.00,5.00,6.00,10.00,9.00,1.00,3.00,0.00,3.00,2.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,3125cb2fe964e26e3e57fca5e,NFG,National Fuel Gas Co,National Fuel Gas is a holding company with su...,Utilities,"5,242,916,355.00",35,31,20,33,...,18.00,-1.00,1.00,-2.00,-3.00,16.00,4.00,0.00,4.00,-6.70
821,daf9afcb9ddd4f0770218af60,RUN,Sunrun Inc.,"Sunrun Inc. engages in the design, development...",Utilities,"10,175,145,133.00",12,21,31,16,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
83,18f31b6b4619dacaaf2194cd5,EVRG,"Evergy, Inc.",Evergy and its subsidiaries provides energy ge...,Utilities,"14,592,514,283.00",26,23,30,38,...,1.00,-2.00,0.00,12.00,-19.00,-7.00,3.00,0.00,4.00,-7.45
425,6e5b1fc2e9811d2cb80e1833c,PCG,PG&E Corporation,PG&E is the holding company for Pacific Gas an...,Utilities,"26,526,689,191.00",2,11,17,9,...,2.00,2.00,33.00,-15.00,2.00,-7.00,11.00,0.00,0.00,25.22
706,ba7b6cf8e6a0bdcb750038aef,ATO,Atmos Energy Corp,Atmos Energy distributes natural gas through r...,Utilities,"12,286,488,973.00",29,4,35,34,...,-3.00,-2.00,-7.00,-2.00,-9.00,-7.00,4.00,0.00,3.00,-20.85

In [175]:
#View columns after adding columns
industry_rankings_2022.columns

Index(['company_perm_id', 'ticker', 'company_name', 'description',
       'industry_name', 'marketcap', 'BENEFITS_22', 'CAREER_22',
       'CLIMATECHANGE_22', 'COMM_22', 'COMMDEV_22', 'CUST_22', 'DEI_22',
       'ENV_22', 'EXPERIENCE_22', 'HEALTH_22', 'JOBS_22', 'PERFORMANCE_22',
       'PHILANTHROPY_22', 'POLLUTION_22', 'PRIORITIZATION_22', 'PRIVACY_22',
       'PRODHARM_22', 'RESOURCES_22', 'RESPONSIBLE_22', 'SHARE_22',
       'SUPPLY_CHAIN_22', 'SUSTPRODUCTSERVICE_22', 'TRANSPARENT_22',
       'WAGES_22', 'WEIGHTED_SCORE_22', 'WORKER_22', 'BENEFITS_21',
       'CAREER_21', 'CLIMATECHANGE_21', 'COMM_21', 'COMMDEV_21', 'CUST_21',
       'DEI_21', 'ENV_21', 'ENVEFFICIENT_21', 'EXPERIENCE_21', 'HEALTH_21',
       'JOBS_21', 'PERFORMANCE_21', 'PHILANTHROPY_21', 'PRIORITIZATION_21',
       'PRIVACY_21', 'PRODHARM_21', 'RESPONSIBLE_21', 'SHARE_21',
       'SUPPLY_CHAIN_21', 'SUSTPRODUCTSERVICE_21', 'TRANSPARENT_21',
       'WAGES_21', 'WEIGHTED_SCORE_21', 'WORKER_21', 'comm_changes',
       'cust_changes', 'env_changes', 'share_changes', 'worker_changes',
       'overall_changes', 'benefits_changes', 'career_changes',
       'climatechange_changes', 'commdev_changes', 'dei_changes',
       'experience_changes', 'health_changes', 'jobs_changes',
       'performance_changes', 'philanthropy_changes', 'prioritization_changes',
       'privacy_changes', 'prodharm_changes', 'responsible_changes',
       'supply_chain_changes', 'sustproductservice_changes',
       'transparent_changes', 'wages_changes', 'pollutionresources_proxy'],
      dtype='object')

In [176]:
#Defining a table as 'industry_stakeholder_ranks' by taking only specific columns from the 'all_ranks' table
#Changing the order in which the columns are called will change the order of how they show up in the 'stakeholder' table
industry_stakeholder_ranks = industry_rankings_2022[['company_perm_id', 'ticker', 'company_name',
                                               'description', 'industry_name', 'marketcap',
                              'WEIGHTED_SCORE_22', 'WEIGHTED_SCORE_21', 'overall_changes',
                              'COMM_22', 'COMM_21', 'comm_changes',
                              'CUST_22', 'CUST_21', 'cust_changes',
                              'ENV_22', 'ENV_21', 'env_changes',
                              'SHARE_22', 'SHARE_21', 'share_changes',
                              'WORKER_22', 'WORKER_21', 'worker_changes']]
industry_stakeholder_ranks

,company_perm_id,ticker,company_name,description,industry_name,marketcap,WEIGHTED_SCORE_22,WEIGHTED_SCORE_21,overall_changes,COMM_22,...,cust_changes,ENV_22,ENV_21,env_changes,SHARE_22,SHARE_21,share_changes,WORKER_22,WORKER_21,worker_changes
656,af66b6de5c616f39fba9361d6,LMT,Lockheed Martin Corp,Lockheed Martin is a global security and aeros...,Aerospace & Defense,"100,263,000,000.00",1,1.00,0.00,3,...,-2.00,1,2.00,1.00,1,1.00,0.00,2,1.00,-1.00
693,b7f5ad4cce9d991bfe96e1872,NOC,Northrop Grumman Corporation,Northrop Grumman is a global security company ...,Aerospace & Defense,"62,432,943,624.00",2,3.00,1.00,1,...,0.00,6,8.00,2.00,4,2.00,-2.00,1,5.00,4.00
899,f24ae0e655f66a765f4580185,RTX,Raytheon Technologies Corp,"Raytheon Technologies Corporation, an aerospac...",Aerospace & Defense,"134,457,000,000.00",3,2.00,-1.00,2,...,3.00,2,7.00,5.00,7,13.00,6.00,4,2.00,-2.00
117,208b13449a1ba16d7e37b4461,TXT,Textron Inc,Textron is a global multi-industry company wit...,Aerospace & Defense,"16,400,174,753.00",4,10.00,6.00,5,...,3.00,3,18.00,15.00,3,9.00,6.00,6,12.00,6.00
227,384a205d8d92a3682a6f035ae,LHX,L3 Harris Technologies,L3Harris Technologies is a technology company ...,Aerospace & Defense,"47,557,339,562.00",5,12.00,7.00,13,...,5.00,5,9.00,4.00,2,10.00,8.00,5,10.00,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,3125cb2fe964e26e3e57fca5e,NFG,National Fuel Gas Co,National Fuel Gas is a holding company with su...,Utilities,"5,242,916,355.00",34,35.00,1.00,33,...,0.00,31,31.00,0.00,35,29.00,-6.00,33,33.00,0.00
821,daf9afcb9ddd4f0770218af60,RUN,Sunrun Inc.,"Sunrun Inc. engages in the design, development...",Utilities,"10,175,145,133.00",35,nan,nan,16,...,nan,38,nan,nan,36,nan,nan,36,nan,nan
83,18f31b6b4619dacaaf2194cd5,EVRG,"Evergy, Inc.",Evergy and its subsidiaries provides energy ge...,Utilities,"14,592,514,283.00",36,34.00,-2.00,38,...,11.00,9,20.00,11.00,29,19.00,-10.00,38,34.00,-4.00
425,6e5b1fc2e9811d2cb80e1833c,PCG,PG&E Corporation,PG&E is the holding company for Pacific Gas an...,Utilities,"26,526,689,191.00",37,20.00,-17.00,9,...,17.00,3,9.00,6.00,20,36.00,16.00,4,10.00,6.00
706,ba7b6cf8e6a0bdcb750038aef,ATO,Atmos Energy Corp,Atmos Energy distributes natural gas through r...,Utilities,"12,286,488,973.00",38,30.00,-8.00,34,...,-1.00,37,31.00,-6.00,38,34.00,-4.00,30,17.00,-13.00

In [177]:
#Exporting to Excel
industry_stakeholder_ranks.to_excel("industry_stakeholder_ranks.xlsx",index = False)
#Converted marketcap to currency

In [178]:
#Defining 'industry_issue_ranks' table as everything from 'all_ranks_22' EXCEPT for the columns explicitly named below
industry_issue_ranks = industry_rankings_2022.drop(['COMM_22','COMM_21',
                                'CUST_22','CUST_21',
                                'ENV_22','ENV_21',
                                'SHARE_22','SHARE_21',
                                'WORKER_22','WORKER_21',
                                'WEIGHTED_SCORE_21'], axis=1)
industry_issue_ranks

,company_perm_id,ticker,company_name,description,industry_name,marketcap,BENEFITS_22,CAREER_22,CLIMATECHANGE_22,COMMDEV_22,...,philanthropy_changes,prioritization_changes,privacy_changes,prodharm_changes,responsible_changes,supply_chain_changes,sustproductservice_changes,transparent_changes,wages_changes,pollutionresources_proxy
656,af66b6de5c616f39fba9361d6,LMT,Lockheed Martin Corp,Lockheed Martin is a global security and aeros...,Aerospace & Defense,"100,263,000,000.00",4,1,2,2,...,-2.00,-1.00,-1.00,-1.00,-4.00,-4.00,1.00,0.00,-2.00,-2.08
693,b7f5ad4cce9d991bfe96e1872,NOC,Northrop Grumman Corporation,Northrop Grumman is a global security company ...,Aerospace & Defense,"62,432,943,624.00",2,4,8,1,...,1.00,-2.00,-8.00,-3.00,3.00,1.00,6.00,1.00,-1.00,-1.23
899,f24ae0e655f66a765f4580185,RTX,Raytheon Technologies Corp,"Raytheon Technologies Corporation, an aerospac...",Aerospace & Defense,"134,457,000,000.00",3,7,4,8,...,4.00,5.00,1.00,2.00,7.00,6.00,3.00,0.00,-3.00,-1.39
117,208b13449a1ba16d7e37b4461,TXT,Textron Inc,Textron is a global multi-industry company wit...,Aerospace & Defense,"16,400,174,753.00",9,5,5,4,...,0.00,2.00,1.00,-2.00,4.00,-1.00,0.00,0.00,3.00,11.47
227,384a205d8d92a3682a6f035ae,LHX,L3 Harris Technologies,L3Harris Technologies is a technology company ...,Aerospace & Defense,"47,557,339,562.00",6,2,3,3,...,-1.00,5.00,6.00,10.00,9.00,1.00,3.00,0.00,3.00,2.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,3125cb2fe964e26e3e57fca5e,NFG,National Fuel Gas Co,National Fuel Gas is a holding company with su...,Utilities,"5,242,916,355.00",35,31,20,29,...,18.00,-1.00,1.00,-2.00,-3.00,16.00,4.00,0.00,4.00,-6.70
821,daf9afcb9ddd4f0770218af60,RUN,Sunrun Inc.,"Sunrun Inc. engages in the design, development...",Utilities,"10,175,145,133.00",12,21,31,36,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
83,18f31b6b4619dacaaf2194cd5,EVRG,"Evergy, Inc.",Evergy and its subsidiaries provides energy ge...,Utilities,"14,592,514,283.00",26,23,30,36,...,1.00,-2.00,0.00,12.00,-19.00,-7.00,3.00,0.00,4.00,-7.45
425,6e5b1fc2e9811d2cb80e1833c,PCG,PG&E Corporation,PG&E is the holding company for Pacific Gas an...,Utilities,"26,526,689,191.00",2,11,17,17,...,2.00,2.00,33.00,-15.00,2.00,-7.00,11.00,0.00,0.00,25.22
706,ba7b6cf8e6a0bdcb750038aef,ATO,Atmos Energy Corp,Atmos Energy distributes natural gas through r...,Utilities,"12,286,488,973.00",29,4,35,38,...,-3.00,-2.00,-7.00,-2.00,-9.00,-7.00,4.00,0.00,3.00,-20.85

In [179]:
industry_issue_ranks.columns

Index(['company_perm_id', 'ticker', 'company_name', 'description',
       'industry_name', 'marketcap', 'BENEFITS_22', 'CAREER_22',
       'CLIMATECHANGE_22', 'COMMDEV_22', 'DEI_22', 'EXPERIENCE_22',
       'HEALTH_22', 'JOBS_22', 'PERFORMANCE_22', 'PHILANTHROPY_22',
       'POLLUTION_22', 'PRIORITIZATION_22', 'PRIVACY_22', 'PRODHARM_22',
       'RESOURCES_22', 'RESPONSIBLE_22', 'SUPPLY_CHAIN_22',
       'SUSTPRODUCTSERVICE_22', 'TRANSPARENT_22', 'WAGES_22',
       'WEIGHTED_SCORE_22', 'BENEFITS_21', 'CAREER_21', 'CLIMATECHANGE_21',
       'COMMDEV_21', 'DEI_21', 'ENVEFFICIENT_21', 'EXPERIENCE_21', 'HEALTH_21',
       'JOBS_21', 'PERFORMANCE_21', 'PHILANTHROPY_21', 'PRIORITIZATION_21',
       'PRIVACY_21', 'PRODHARM_21', 'RESPONSIBLE_21', 'SUPPLY_CHAIN_21',
       'SUSTPRODUCTSERVICE_21', 'TRANSPARENT_21', 'WAGES_21', 'comm_changes',
       'cust_changes', 'env_changes', 'share_changes', 'worker_changes',
       'overall_changes', 'benefits_changes', 'career_changes',
       'climatechange_changes', 'commdev_changes', 'dei_changes',
       'experience_changes', 'health_changes', 'jobs_changes',
       'performance_changes', 'philanthropy_changes', 'prioritization_changes',
       'privacy_changes', 'prodharm_changes', 'responsible_changes',
       'supply_chain_changes', 'sustproductservice_changes',
       'transparent_changes', 'wages_changes', 'pollutionresources_proxy'],
      dtype='object')

In [180]:
#Exporting to Excel
industry_issue_ranks.to_excel("industry_issue_ranks.xlsx",index = False)
#Converted marketcap to currency

In [181]:
#Obtaining Taxonomy Data, Issue Data, Metric Data
taxonomy_metadata = jc_api.get_data("ft_ss_data_taxonomy_mapping_AYR_2022",
                               ["fields=parent_perm_id, child_perm_id",
                               "weight_schema_perm_id=in: 'f7755752ab50b30bca10cb7856f53ec3'" 
                               ])
issue_metadata = jc_api.get_data("ft_ss_data_taxonomy_AYR_2022",
                               ["fields=perm_id, slug, name, type, description",
                               "type=in: 'ISSUE'" 
                               ])
metric_metadata = jc_api.get_data("ft_ss_data_taxonomy_AYR_2022",
                               ["fields=perm_id, slug, name, type, description",
                               "type=in: 'METRIC'" 
                               ])
stakeholder_metadata = jc_api.get_data("ft_ss_data_taxonomy_AYR_2022",
                               ["fields=perm_id, slug, name, type, description",
                               "type=in: 'STAKEHOLDER'" 
                               ])

stakeholder_metadata
#stakeholder_metadata
#issue_metadata

,perm_id,slug,name,type,description
0,9815d1f90c28664e06ad058c687c17b6,WORKER,Workers,STAKEHOLDER,Includes Issues like paying a fair and a livab...
1,0abe3d1d4c7e88552c35a3a3b3fa46cf,COMM,Communities,STAKEHOLDER,Includes Issues like upholding human rights st...
2,f87b196ed3bb2e90cb0957120e99434a,CUST,Customers,STAKEHOLDER,Includes Issues like protecting customer priva...
3,b71cb1b88d2a81035be0b8c0ef6bb016,SHARE,Shareholders & Governance,STAKEHOLDER,Includes Issues like acting ethically and with...
4,3c59f75b642202423390cb724fd1126d,ENV,Environment,STAKEHOLDER,"Includes Issues like minimizing pollution, hel..."

In [182]:
#Merging Taxonomy Metadata onto the Issue Metadata so that we can match again child_perm_id to metric_metadata.perm_id
issue_tax = pd.merge(issue_metadata, taxonomy_metadata, how="left", left_on="perm_id", right_on="parent_perm_id")
issue_tax

,perm_id,slug,name,type,description,parent_perm_id,child_perm_id
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,68ecfd06bcaffeb44a34f51ab0707fca,5bbffdb3fca9936bf25dbcbc8795c5f7
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,68ecfd06bcaffeb44a34f51ab0707fca,a0748703138d3004f2115ff8df41706e
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,68ecfd06bcaffeb44a34f51ab0707fca,b1f16a75d6a578e80eb0fd9874c66414
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,68ecfd06bcaffeb44a34f51ab0707fca,b5f913b982e593905deb85cd1cd8b232
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,68ecfd06bcaffeb44a34f51ab0707fca,e61c60264e4b01e9246be87467c62b54
...,...,...,...,...,...,...,...
132,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,96fca97febd5a875ebef31605d774d68,8f70f13ef6a527ddc9f7b06c05c7bdf5
133,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,96fca97febd5a875ebef31605d774d68,8f70f13ef6a527ddc9f7b06c05c7bdf5
134,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,96fca97febd5a875ebef31605d774d68,8f70f13ef6a527ddc9f7b06c05c7bdf5
135,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,c67abf48acdc78ae4071099bedc0843b,033bbf5acc826b287f27753d0f06bec8
136,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,c67abf48acdc78ae4071099bedc0843b,033bbf5acc826b287f27753d0f06bec8

In [183]:
issue_tax = issue_tax.drop(['parent_perm_id'], axis=1)
issue_tax

,perm_id,slug,name,type,description,child_perm_id
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54
...,...,...,...,...,...,...
132,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5
133,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5
134,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5
135,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8
136,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8

In [184]:
issue_tax.rename(columns={'perm_id': 'issue_perm_id'}, inplace=True)
issue_tax

,issue_perm_id,slug,name,type,description,child_perm_id
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54
...,...,...,...,...,...,...
132,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5
133,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5
134,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5
135,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8
136,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8

In [185]:
#Merging Taxonomy Metadata onto the Issue Metadata so that we can match again child_perm_id to metric_metadata.perm_id
issue_tax = pd.merge(issue_tax, metric_metadata, how="left", left_on="child_perm_id", right_on="perm_id")
issue_tax

,issue_perm_id,slug_x,name_x,type_x,description_x,child_perm_id,perm_id,slug_y,name_y,type_y,description_y
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7,5bbffdb3fca9936bf25dbcbc8795c5f7,CEO_MEDIAN,CEO-to-Median Worker Pay,METRIC,NaN
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e,a0748703138d3004f2115ff8df41706e,WAGE_VIOLATIONS,Wage Violations,METRIC,NaN
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage,METRIC,NaN
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232,b5f913b982e593905deb85cd1cd8b232,FAIR_PAY_SCORE,Fair Pay Score,METRIC,NaN
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,ISSUE,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54,e61c60264e4b01e9246be87467c62b54,FAIR_PAY_RATING,Fair Pay Rating,METRIC,NaN
...,...,...,...,...,...,...,...,...,...,...,...
132,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,METRIC,NaN
133,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,METRIC,NaN
134,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,ISSUE,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,METRIC,NaN
135,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,METRIC,NaN
136,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,ISSUE,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,METRIC,NaN

In [186]:
issue_tax = issue_tax.drop(['perm_id','type_x','type_y'], axis=1)
issue_tax

,issue_perm_id,slug_x,name_x,description_x,child_perm_id,slug_y,name_y,description_y
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7,CEO_MEDIAN,CEO-to-Median Worker Pay,NaN
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e,WAGE_VIOLATIONS,Wage Violations,NaN
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage,NaN
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232,FAIR_PAY_SCORE,Fair Pay Score,NaN
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54,FAIR_PAY_RATING,Fair Pay Rating,NaN
...,...,...,...,...,...,...,...,...
132,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN
133,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN
134,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN
135,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,NaN
136,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,NaN

In [187]:
issue_tax.rename(columns={'slug_x': 'issue_slug',
                         'name_x':'issue_name',
                         'description_x':'issue_description',
                         'child_perm_id':'metric_perm_id',
                            'slug_y':'metric_slug',
                         'name_y':'metric_name',
                         'description_y':'metric_description'}, inplace=True)
issue_tax

,issue_perm_id,issue_slug,issue_name,issue_description,metric_perm_id,metric_slug,metric_name,metric_description
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7,CEO_MEDIAN,CEO-to-Median Worker Pay,NaN
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e,WAGE_VIOLATIONS,Wage Violations,NaN
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage,NaN
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232,FAIR_PAY_SCORE,Fair Pay Score,NaN
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54,FAIR_PAY_RATING,Fair Pay Rating,NaN
...,...,...,...,...,...,...,...,...
132,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN
133,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN
134,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN
135,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,NaN
136,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,NaN

In [188]:
issue_tax.columns

Index(['issue_perm_id', 'issue_slug', 'issue_name', 'issue_description',
       'metric_perm_id', 'metric_slug', 'metric_name', 'metric_description'],
      dtype='object')

In [189]:
issue_tax.drop_duplicates(subset='metric_perm_id', keep='first', inplace=True)
issue_tax

,issue_perm_id,issue_slug,issue_name,issue_description,metric_perm_id,metric_slug,metric_name,metric_description
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7,CEO_MEDIAN,CEO-to-Median Worker Pay,NaN
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e,WAGE_VIOLATIONS,Wage Violations,NaN
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage,NaN
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232,FAIR_PAY_SCORE,Fair Pay Score,NaN
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54,FAIR_PAY_RATING,Fair Pay Rating,NaN
...,...,...,...,...,...,...,...,...
126,a8091ff308177c00204dee0cd4a7d438,PHILANTHROPY,Community Support,Gives back to local communities with donations...,2cdb8137807cda3ac0c9c76174caf46e,EMPLOYEE_LED,Employee-Led Giving and Volunteering,NaN
127,a8091ff308177c00204dee0cd4a7d438,PHILANTHROPY,Community Support,Gives back to local communities with donations...,5ccc7f0dac0677412a14c91b1050e40b,GIVING_TRANSPARENCY,Transparent Charitable Giving,NaN
128,a8091ff308177c00204dee0cd4a7d438,PHILANTHROPY,Community Support,Gives back to local communities with donations...,f6ea0f41113689ee9d03c3fa6b537b91,CHARITABLE_GIVING,Charitable Giving Ratio,NaN
132,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN
135,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,NaN

In [194]:
#Merging Taxonomy Metadata onto the Issue Metadata so that we can match again child_perm_id to metric_metadata.perm_id
adding_stakeholder = pd.merge(issue_tax,
                              taxonomy_metadata.drop_duplicates(subset=['child_perm_id']),
                              how="inner",
                              left_on="issue_perm_id",
                              right_on="child_perm_id")
#adding_stakeholder.parent_perm_id.unique()
adding_stakeholder

,issue_perm_id,issue_slug,issue_name,issue_description,metric_perm_id,metric_slug,metric_name,metric_description,parent_perm_id,child_perm_id
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7,CEO_MEDIAN,CEO-to-Median Worker Pay,NaN,9815d1f90c28664e06ad058c687c17b6,68ecfd06bcaffeb44a34f51ab0707fca
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e,WAGE_VIOLATIONS,Wage Violations,NaN,9815d1f90c28664e06ad058c687c17b6,68ecfd06bcaffeb44a34f51ab0707fca
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage,NaN,9815d1f90c28664e06ad058c687c17b6,68ecfd06bcaffeb44a34f51ab0707fca
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232,FAIR_PAY_SCORE,Fair Pay Score,NaN,9815d1f90c28664e06ad058c687c17b6,68ecfd06bcaffeb44a34f51ab0707fca
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54,FAIR_PAY_RATING,Fair Pay Rating,NaN,9815d1f90c28664e06ad058c687c17b6,68ecfd06bcaffeb44a34f51ab0707fca
...,...,...,...,...,...,...,...,...,...,...
61,a8091ff308177c00204dee0cd4a7d438,PHILANTHROPY,Community Support,Gives back to local communities with donations...,2cdb8137807cda3ac0c9c76174caf46e,EMPLOYEE_LED,Employee-Led Giving and Volunteering,NaN,0abe3d1d4c7e88552c35a3a3b3fa46cf,a8091ff308177c00204dee0cd4a7d438
62,a8091ff308177c00204dee0cd4a7d438,PHILANTHROPY,Community Support,Gives back to local communities with donations...,5ccc7f0dac0677412a14c91b1050e40b,GIVING_TRANSPARENCY,Transparent Charitable Giving,NaN,0abe3d1d4c7e88552c35a3a3b3fa46cf,a8091ff308177c00204dee0cd4a7d438
63,a8091ff308177c00204dee0cd4a7d438,PHILANTHROPY,Community Support,Gives back to local communities with donations...,f6ea0f41113689ee9d03c3fa6b537b91,CHARITABLE_GIVING,Charitable Giving Ratio,NaN,0abe3d1d4c7e88552c35a3a3b3fa46cf,a8091ff308177c00204dee0cd4a7d438
64,96fca97febd5a875ebef31605d774d68,RESOURCES,Resource Efficiency,Uses natural resources efficiently and minimiz...,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use,NaN,3c59f75b642202423390cb724fd1126d,96fca97febd5a875ebef31605d774d68
65,c67abf48acdc78ae4071099bedc0843b,POLLUTION,Pollution Reduction,Minimizes pollution that lowers air quality an...,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution,NaN,3c59f75b642202423390cb724fd1126d,c67abf48acdc78ae4071099bedc0843b

In [195]:
issue_tax=pd.merge(adding_stakeholder,stakeholder_metadata,how='left',left_on='parent_perm_id',right_on='perm_id')
issue_tax = issue_tax.drop(['parent_perm_id', 'child_perm_id', 'perm_id', 'name', 'type',
       'description'], axis=1)
issue_tax.rename(columns={'slug':'stakeholder_slug'},inplace=True)
#Sort/order by ascending order
issue_tax.sort_values(by=['stakeholder_slug','issue_slug','metric_slug'], inplace=True)
issue_tax

,issue_perm_id,issue_slug,issue_name,issue_description,metric_perm_id,metric_slug,metric_name,metric_description,stakeholder_slug
51,cd067e93c7f1d7da998e44555a08b212,COMMDEV,Community Development,Contributes to community development by suppor...,c3516d47dc0a965e3613305adafb1c13,COMMUNITY_IMPACT,Community Impacts Controversies,NaN,COMM
49,cd067e93c7f1d7da998e44555a08b212,COMMDEV,Community Development,Contributes to community development by suppor...,0e28159ee613543840f4bec2f5f6dc18,CREATES_OPPORTUNITIES,Opportunities for Local Businesses,NaN,COMM
50,cd067e93c7f1d7da998e44555a08b212,COMMDEV,Community Development,Contributes to community development by suppor...,993d5a2cd2fa21b9c8aa835ecc873fae,LOCAL_ENGAGEMENT,Local Community Engagement,NaN,COMM
52,cd067e93c7f1d7da998e44555a08b212,COMMDEV,Community Development,Contributes to community development by suppor...,ae12bd72dc14d0e9189c98e47c3afa6b,SUPPORTS_EDUCATION,Local School Support,NaN,COMM
33,922cfffc942178f9edf8a5ca5a26d20e,JOBS,Local Job Creation,Creates jobs in the U.S. and provides employme...,544a7bcf077fe6b89563975690784797,CREATES_LOCAL_JOBS,Local Employment Pipeline,NaN,COMM
...,...,...,...,...,...,...,...,...,...
0,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,5bbffdb3fca9936bf25dbcbc8795c5f7,CEO_MEDIAN,CEO-to-Median Worker Pay,NaN,WORKER
4,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,e61c60264e4b01e9246be87467c62b54,FAIR_PAY_RATING,Fair Pay Rating,NaN,WORKER
3,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b5f913b982e593905deb85cd1cd8b232,FAIR_PAY_SCORE,Fair Pay Score,NaN,WORKER
2,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage,NaN,WORKER
1,68ecfd06bcaffeb44a34f51ab0707fca,WAGES,Living Wage,Pays workers fairly and offers a living wage t...,a0748703138d3004f2115ff8df41706e,WAGE_VIOLATIONS,Wage Violations,NaN,WORKER

In [196]:
issue_tax.to_excel("issue_tax.xlsx",index = False)

In [55]:
metrics = issue_tax.drop(['issue_slug','issue_name',
                                'issue_description','issue_perm_id', 'metric_description'], axis=1)
metrics

,metric_perm_id,metric_slug,metric_name
0,5bbffdb3fca9936bf25dbcbc8795c5f7,CEO_MEDIAN,CEO-to-Median Worker Pay
1,a0748703138d3004f2115ff8df41706e,WAGE_VIOLATIONS,Wage Violations
2,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage
3,b5f913b982e593905deb85cd1cd8b232,FAIR_PAY_SCORE,Fair Pay Score
4,e61c60264e4b01e9246be87467c62b54,FAIR_PAY_RATING,Fair Pay Rating
...,...,...,...
126,2cdb8137807cda3ac0c9c76174caf46e,EMPLOYEE_LED,Employee-Led Giving and Volunteering
127,5ccc7f0dac0677412a14c91b1050e40b,GIVING_TRANSPARENCY,Transparent Charitable Giving
128,f6ea0f41113689ee9d03c3fa6b537b91,CHARITABLE_GIVING,Charitable Giving Ratio
132,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use
135,033bbf5acc826b287f27753d0f06bec8,AIR,Air Pollution

In [56]:
metric_rankings=jc_api.get_data("ft_ss_model_ranking_RANKING_2022_WEIGHT_SCHEMA22_AYR_2022",
                               ["fields=company_perm_id, data_perm_id, model_slug, value_type, industry_rank, overall_rank",
                               "value_type=in: 'rank'"])
metric_rankings

,company_perm_id,data_perm_id,model_slug,value_type,industry_rank,overall_rank
0,00aa86290f0973a72bca4ef3b,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,rank,16,384
1,00aa86290f0973a72bca4ef3b,033bbf5acc826b287f27753d0f06bec8,AIR,rank,32,705
2,00aa86290f0973a72bca4ef3b,c23dbed88c604671832d691dadaf73d8,ENERGY,rank,9,307
3,00aa86290f0973a72bca4ef3b,4e086b69f887883d34afb2380fb59d5e,PRODUCTSERVICE,rank,5,263
4,00aa86290f0973a72bca4ef3b,f76fe101539f2f883adf0bc99f582e79,CLIMATECOMMIT,rank,14,413
...,...,...,...,...,...,...
87763,ffedba4233ac1a8729cd5749d,b71cb1b88d2a81035be0b8c0ef6bb016,SHARE,rank,10,240
87764,ffedba4233ac1a8729cd5749d,f87b196ed3bb2e90cb0957120e99434a,CUST,rank,2,225
87765,ffedba4233ac1a8729cd5749d,0abe3d1d4c7e88552c35a3a3b3fa46cf,COMM,rank,7,223
87766,ffedba4233ac1a8729cd5749d,9815d1f90c28664e06ad058c687c17b6,WORKER,rank,7,121
87767,ffedba4233ac1a8729cd5749d,18a8d4f3fb7b7e63b4fffc362721ff4e,WEIGHTED_SCORE,rank,2,90

In [57]:
metric_rankings = pd.merge(metric_rankings, metrics, how="inner", left_on="data_perm_id", right_on="metric_perm_id")
metric_rankings

,company_perm_id,data_perm_id,model_slug,value_type,industry_rank,overall_rank,metric_perm_id,metric_slug,metric_name
0,00aa86290f0973a72bca4ef3b,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,rank,16,384,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use
1,00dae748aa57b455fb29eac00,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,rank,9,655,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use
2,010e3acd01fb1bb37db745be9,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,rank,9,186,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use
3,01722398f1dd91d629c842eae,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,rank,8,584,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use
4,01d76805a4a4900d37767bcf2,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,rank,30,564,8f70f13ef6a527ddc9f7b06c05c7bdf5,WASTE,Resource Use
...,...,...,...,...,...,...,...,...,...
62959,fe9668a59a7386ac1e898d980,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,rank,40,929,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage
62960,feba29952d39a2b39d6b58481,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,rank,28,651,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage
62961,fee1881a18aa180338c3fe312,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,rank,51,741,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage
62962,ff7db7310ab5270accf0422e1,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,rank,11,324,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage
62963,ffedba4233ac1a8729cd5749d,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,rank,5,384,b1f16a75d6a578e80eb0fd9874c66414,LIVING_WAGE,Living Wage

In [58]:
metric_rankings = metric_rankings.drop(['data_perm_id','metric_perm_id',
                                'model_slug','value_type'], axis=1)
metric_rankings

,company_perm_id,industry_rank,overall_rank,metric_slug,metric_name
0,00aa86290f0973a72bca4ef3b,16,384,WASTE,Resource Use
1,00dae748aa57b455fb29eac00,9,655,WASTE,Resource Use
2,010e3acd01fb1bb37db745be9,9,186,WASTE,Resource Use
3,01722398f1dd91d629c842eae,8,584,WASTE,Resource Use
4,01d76805a4a4900d37767bcf2,30,564,WASTE,Resource Use
...,...,...,...,...,...
62959,fe9668a59a7386ac1e898d980,40,929,LIVING_WAGE,Living Wage
62960,feba29952d39a2b39d6b58481,28,651,LIVING_WAGE,Living Wage
62961,fee1881a18aa180338c3fe312,51,741,LIVING_WAGE,Living Wage
62962,ff7db7310ab5270accf0422e1,11,324,LIVING_WAGE,Living Wage
62963,ffedba4233ac1a8729cd5749d,5,384,LIVING_WAGE,Living Wage

In [59]:
metric_rankings = metric_rankings[['company_perm_id','metric_slug','metric_name','industry_rank','overall_rank']]
metric_rankings

,company_perm_id,metric_slug,metric_name,industry_rank,overall_rank
0,00aa86290f0973a72bca4ef3b,WASTE,Resource Use,16,384
1,00dae748aa57b455fb29eac00,WASTE,Resource Use,9,655
2,010e3acd01fb1bb37db745be9,WASTE,Resource Use,9,186
3,01722398f1dd91d629c842eae,WASTE,Resource Use,8,584
4,01d76805a4a4900d37767bcf2,WASTE,Resource Use,30,564
...,...,...,...,...,...
62959,fe9668a59a7386ac1e898d980,LIVING_WAGE,Living Wage,40,929
62960,feba29952d39a2b39d6b58481,LIVING_WAGE,Living Wage,28,651
62961,fee1881a18aa180338c3fe312,LIVING_WAGE,Living Wage,51,741
62962,ff7db7310ab5270accf0422e1,LIVING_WAGE,Living Wage,11,324
62963,ffedba4233ac1a8729cd5749d,LIVING_WAGE,Living Wage,5,384

In [60]:
overall_metric_rankings = metric_rankings.pivot(index ='company_perm_id',
                                                    columns ='metric_slug',
                                                    values ='overall_rank')
overall_metric_rankings

metric_slug,AIR,ANTICOMPETITIVE_CONT,AVOIDS_EXPLOITATION,BENEFIT_PACKAGE,BENEFIT_QUALITY,BOARD_DIVERSITY,BOARD_ESG_OVERSIGHT,BOARD_INDEPENDENCE,CAREERDEV,CEO_MEDIAN,...,SAFETY_VIOLATIONS,SECFILINGSREVIEW,SO_FINMGMT,SO_FREE_CASH_FLOW,SUPPLIER_REQUIREMENTS,SUPPLY_CHAIN_DISCLOSURE,SUPPORTS_EDUCATION,WAGE_VIOLATIONS,WASTE,WORKLIFE
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,705,1,1,754,431,403,464,211,906,366,...,1,1,1,112,256,99,331,1,384,711
00dae748aa57b455fb29eac00,359,1,1,405,439,245,73,646,441,378,...,1,1,1,1,1,99,331,1,655,126
010e3acd01fb1bb37db745be9,97,1,950,499,491,8,1,16,793,326,...,1,1,1,283,11,1,1,1,186,151
01722398f1dd91d629c842eae,677,1,1,499,27,425,1,277,1,528,...,1,1,1,803,256,99,1,1,584,530
01d76805a4a4900d37767bcf2,571,1,1,312,305,516,464,396,217,408,...,1,1,1,112,256,44,1,1,564,202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,187,1,945,164,828,76,218,912,527,931,...,637,1,1,283,11,36,331,1,129,121
feba29952d39a2b39d6b58481,866,1,1,499,419,802,464,158,270,538,...,1,1,1,112,11,99,331,1,789,293
fee1881a18aa180338c3fe312,760,1,1,499,632,569,464,696,655,417,...,1,1,1,112,88,99,331,1,722,402
ff7db7310ab5270accf0422e1,176,1,1,267,323,351,218,579,345,187,...,674,1,1,283,88,99,331,1,421,618
ffedba4233ac1a8729cd5749d,155,1,1,293,521,231,410,554,74,274,...,690,1,1,283,393,47,1,1,317,34

In [61]:
overall_metric_rankings = pd.merge(base, overall_metric_rankings, how="left", on="company_perm_id")
overall_metric_rankings

,company_perm_id,ticker,company_name,description,industry_name,marketcap,AIR,ANTICOMPETITIVE_CONT,AVOIDS_EXPLOITATION,BENEFIT_PACKAGE,...,SAFETY_VIOLATIONS,SECFILINGSREVIEW,SO_FINMGMT,SO_FREE_CASH_FLOW,SUPPLIER_REQUIREMENTS,SUPPLY_CHAIN_DISCLOSURE,SUPPORTS_EDUCATION,WAGE_VIOLATIONS,WASTE,WORKLIFE
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00",705,1,1,754,...,1,1,1,112,256,99,331,1,384,711
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00",359,1,1,405,...,1,1,1,1,1,99,331,1,655,126
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00",97,1,950,499,...,1,1,1,283,11,1,1,1,186,151
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00",677,1,1,499,...,1,1,1,803,256,99,1,1,584,530
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00",571,1,1,312,...,1,1,1,112,256,44,1,1,564,202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00",187,1,945,164,...,637,1,1,283,11,36,331,1,129,121
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00",866,1,1,499,...,1,1,1,112,11,99,331,1,789,293
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00",760,1,1,499,...,1,1,1,112,88,99,331,1,722,402
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00",176,1,1,267,...,674,1,1,283,88,99,331,1,421,618
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00",155,1,1,293,...,690,1,1,283,393,47,1,1,317,34

In [62]:
industry_metric_rankings = metric_rankings.pivot(index ='company_perm_id',
                                                    columns ='metric_slug',
                                                    values ='industry_rank')
industry_metric_rankings

metric_slug,AIR,ANTICOMPETITIVE_CONT,AVOIDS_EXPLOITATION,BENEFIT_PACKAGE,BENEFIT_QUALITY,BOARD_DIVERSITY,BOARD_ESG_OVERSIGHT,BOARD_INDEPENDENCE,CAREERDEV,CEO_MEDIAN,...,SAFETY_VIOLATIONS,SECFILINGSREVIEW,SO_FINMGMT,SO_FREE_CASH_FLOW,SUPPLIER_REQUIREMENTS,SUPPLY_CHAIN_DISCLOSURE,SUPPORTS_EDUCATION,WAGE_VIOLATIONS,WASTE,WORKLIFE
company_perm_id,,,,,,,,,,,,,,,,,,,,,
00aa86290f0973a72bca4ef3b,32,1,1,40,25,17,18,11,53,23,...,1,1,1,11,13,2,13,1,16,40
00dae748aa57b455fb29eac00,8,1,1,7,10,6,1,6,6,5,...,1,1,1,1,1,3,7,1,9,4
010e3acd01fb1bb37db745be9,4,1,20,9,13,1,1,1,19,11,...,1,1,1,6,1,1,1,1,9,3
01722398f1dd91d629c842eae,11,1,1,6,1,3,1,3,1,9,...,1,1,1,8,2,1,1,1,8,5
01d76805a4a4900d37767bcf2,28,1,1,19,15,25,23,20,14,16,...,1,1,1,6,10,2,1,1,30,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fe9668a59a7386ac1e898d980,16,1,52,8,14,12,6,51,27,52,...,24,1,1,21,2,6,15,1,9,6
feba29952d39a2b39d6b58481,22,1,1,19,21,26,17,7,16,19,...,1,1,1,6,1,11,18,1,26,12
fee1881a18aa180338c3fe312,39,1,1,26,44,28,18,40,31,29,...,1,1,1,11,1,2,13,1,38,18
ff7db7310ab5270accf0422e1,5,1,1,10,15,13,7,36,9,12,...,44,1,1,26,1,2,13,1,18,30
ffedba4233ac1a8729cd5749d,4,1,1,4,20,6,22,20,4,7,...,15,1,1,7,12,2,1,1,12,1

In [63]:
industry_metric_rankings = pd.merge(base, industry_metric_rankings, how="left", on="company_perm_id")
industry_metric_rankings

,company_perm_id,ticker,company_name,description,industry_name,marketcap,AIR,ANTICOMPETITIVE_CONT,AVOIDS_EXPLOITATION,BENEFIT_PACKAGE,...,SAFETY_VIOLATIONS,SECFILINGSREVIEW,SO_FINMGMT,SO_FREE_CASH_FLOW,SUPPLIER_REQUIREMENTS,SUPPLY_CHAIN_DISCLOSURE,SUPPORTS_EDUCATION,WAGE_VIOLATIONS,WASTE,WORKLIFE
0,00aa86290f0973a72bca4ef3b,PKI,PerkinElmer Inc,"PerkinElmer provides products, services, and s...",Health Care Equipment & Services,"19,023,528,802.00",32,1,1,40,...,1,1,1,11,13,2,13,1,16,40
1,00dae748aa57b455fb29eac00,IPG,"The Interpublic Group of Companies, Inc.",Interpublic Group's services include consumer ...,Media,"14,996,930,573.00",8,1,1,7,...,1,1,1,1,1,3,7,1,9,4
2,010e3acd01fb1bb37db745be9,HPQ,HP Inc.,HP is a global provider of imaging and printin...,Technology Hardware,"31,682,740,108.00",4,1,20,9,...,1,1,1,6,1,1,1,1,9,3
3,01722398f1dd91d629c842eae,LNG,Cheniere Energy Inc,Cheniere Energy specializes in developing and ...,Energy Equipment & Services,"26,874,725,100.00",11,1,1,6,...,1,1,1,8,2,1,1,1,8,5
4,01d76805a4a4900d37767bcf2,VRSK,Verisk Analytics Inc,Verisk is a data analytics provider with custo...,Commercial Support Services,"34,133,691,717.00",28,1,1,19,...,1,1,1,6,10,2,1,1,30,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,fe9668a59a7386ac1e898d980,GPS,"The Gap, Inc.","Gap Inc. is a global retail company, offering ...",Retail,"8,552,629,178.00",16,1,52,8,...,24,1,1,21,2,6,15,1,9,6
950,feba29952d39a2b39d6b58481,ENTG,"Entegris, Inc.","Entegris develops, manufacturers, and offers m...",Semiconductors & Equipment,"17,342,913,983.00",22,1,1,19,...,1,1,1,6,1,11,18,1,26,12
951,fee1881a18aa180338c3fe312,IART,Integra LifeSciences Holdings,Integra Lifesciences is a medical technology c...,Health Care Equipment & Services,"5,683,745,222.00",39,1,1,26,...,1,1,1,11,1,2,13,1,38,18
952,ff7db7310ab5270accf0422e1,MDT,Medtronic PLC,"Medtronic researches, designs, manufactures, a...",Health Care Equipment & Services,"167,719,000,000.00",5,1,1,10,...,44,1,1,26,1,2,13,1,18,30
953,ffedba4233ac1a8729cd5749d,ECL,Ecolab Inc,Ecolab provides products and services globally...,Chemicals,"62,753,232,365.00",4,1,1,4,...,15,1,1,7,12,2,1,1,12,1

In [64]:
industry_metric_rankings.sort_values(by=['industry_name'], inplace=True)
industry_metric_rankings

,company_perm_id,ticker,company_name,description,industry_name,marketcap,AIR,ANTICOMPETITIVE_CONT,AVOIDS_EXPLOITATION,BENEFIT_PACKAGE,...,SAFETY_VIOLATIONS,SECFILINGSREVIEW,SO_FINMGMT,SO_FREE_CASH_FLOW,SUPPLIER_REQUIREMENTS,SUPPLY_CHAIN_DISCLOSURE,SUPPORTS_EDUCATION,WAGE_VIOLATIONS,WASTE,WORKLIFE
840,e40c92fd97e17025cb10a58d3,GD,General Dynamics Corp,General Dynamics is a global aerospace and def...,Aerospace & Defense,"57,345,125,668.00",5,1,17,14,...,11,1,1,3,4,2,10,1,6,9
206,326df96af72c2381429e3a3e9,SPR,Spirit Aerosystems Holdings Inc,Spirit is an independent non-Original Equipmen...,Aerospace & Defense,"4,656,831,527.00",9,1,1,8,...,16,16,1,12,3,2,10,14,15,10
882,ed61cd72b42031638ea626d73,SPCE,Virgin Galactic,"Virgin Galactic Holdings, Inc., an integrated ...",Aerospace & Defense,"6,189,695,498.00",17,1,1,14,...,1,16,17,16,16,2,10,1,17,13
89,1a4c722e68ffc6f52b2470f31,BWXT,"BWX Technologies, Inc.",BWX Technologies manufactures and develops nuc...,Aerospace & Defense,"5,412,688,806.00",12,1,1,3,...,17,1,1,12,7,2,1,1,5,8
668,b188c738f1a3322434a74341d,BA,The Boeing Company,Boeing is one of the world's major aerospace c...,Aerospace & Defense,"127,453,000,000.00",3,1,16,1,...,9,1,1,12,7,2,1,15,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,a4ff42a1d6c5e9458bfeb7542,EIX,Edison International,Edison International is a holding company oper...,Utilities,"21,491,291,623.00",9,1,1,9,...,30,1,1,10,21,5,1,1,13,24
818,d9d8b9b691cb96a3651d99e94,SO,The Southern Company,"Through its public utility subsidiaries, South...",Utilities,"66,981,320,994.00",13,1,1,8,...,17,1,1,10,31,5,21,1,2,26
729,bf4378ef953a8d087e35b789c,UGI,UGI Corp,"Through its subsidiaries and affiliates, UGI d...",Utilities,"9,344,540,282.00",6,1,1,15,...,33,1,1,1,12,5,1,1,34,5
70,15866e8ffd87b1cd8d198d476,CNP,CenterPoint Energy Inc,CenterPoint is a public utility holding compan...,Utilities,"15,753,097,317.00",15,1,1,27,...,35,1,1,10,29,5,1,1,4,12
911,f61c5fe4aec3f3550f9f63be6,PNW,Pinnacle West Capital Corp,"Through its subsidiary APS, Pinnacle West Capi...",Utilities,"7,616,410,758.00",19,1,1,19,...,1,1,1,10,21,5,1,1,21,34

In [65]:
industry_metric_rankings.to_excel("industry_metric_rankings.xlsx",index = False)

overall_metric_rankings.to_excel("overall_metric_rankings.xlsx",index = False)

array(['9815d1f90c28664e06ad058c687c17b6',
       '0abe3d1d4c7e88552c35a3a3b3fa46cf',
       'b71cb1b88d2a81035be0b8c0ef6bb016',
       'f87b196ed3bb2e90cb0957120e99434a',
       '3c59f75b642202423390cb724fd1126d'], dtype=object)